### ISSUE TITLE
[FAQ] Add entry about why packages keep maintenance mode open

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud.org#1023]
Context: https://github.com/owncloud/core/issues/25635#issuecomment-240402410

**Comment by PVince81** [comment]
@RealRancor @jnweiger do we have any reference to why it was decided to leave package upgrades in maintenance mode ? This could be added to the FAQ.

**Comment by PVince81** [comment]
also see https://central.owncloud.org/t/config-switch-to-decide-in-which-mode-oc-goes-after-a-successful-occ-upgrade/1754

**Comment by RealRancor** [comment]
From what i can remember this behavior was changed because in the old behavior the "Update now" button was shown to everyone and people complained about that.

**Comment by hurradieweltgehtunter** [comment]
Please reopen if still relevant after relaunch
