### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by meowncloud** [owncloud/owncloud.org#1034]
respected sir 
i am the new admin of owncloud server , i how new owncloud server own
machine 

i want to post my problem like

Internal Server Error
The server encountered an internal error and was unable to complete your
request.
Please contact the server administrator if this error reappears multiple
times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: 39.42.22.6
Request ID: NbSVCH+q35PajAhq9+xl

what i can do to help any

**Comment by RealRancor** [comment]
@meowncloud Please close here. This is a issue tracker for reporting problems or suggestions to the main page at https://www.owncloud.org.

Instead use the support forums at https://central.owncloud.org/ and make sure that you're filling out the issue template there shown when creating a new thread.

**Comment by Kawohl** [comment]
Wrong here, i'll close
