### ISSUE TITLE
File not found message trying to download a Desktop client

### ISSUE THREAD

**Issue by davitol** [owncloud/owncloud.org#1046]
![screen shot 2016-09-06 at 09 37 24](https://cloud.githubusercontent.com/assets/10596560/18265857/0b9a2b06-7418-11e6-9293-faa39d0effdb.png)

Mac and Windows client:

File not found

**Comment by davitol** [comment]
same for the Testpilots

**Comment by davitol** [comment]
@danimo Maybe ?

**Comment by guruz** [comment]
You can send a PR that changes https://github.com/owncloud/owncloud.org/blame/master/strings.php#L33

@danimo How can we get this to staging and then to the real webserver? Who to ask?

**Comment by guruz** [comment]
-> https://github.com/owncloud/owncloud.org/pull/1066
