### ISSUE TITLE
Script to render changelog to HTML

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud.org#1047]
After a release, usually the changelog HTML page needs to be updated manually with some regexp magic from the original changelog.

Ideal would be to have a script that generates the changelog.
I see that we have a Gruntfile, maybe it could be a small node app that parses the changelog and outputs HTML using templates (handlebars?)

**Comment by PVince81** [comment]
Basically the script would take a full changelog file and regenerate the full HTML page.
No need to just render snippets.

**Comment by PVince81** [comment]
This could do: https://github.com/RobinQu/grunt-render-handlebars

**Comment by PVince81** [comment]
Hmm, on the other hand I see that the changelog page is already a php file, so if we'd just read in the changelog file and render it line by line in HTML, that would do too...

**Comment by PVince81** [comment]
This one looks better maintained https://github.com/Techtribe/grunt-static-handlebars

**Comment by PVince81** [comment]
Or use `sed`, trying that for now:

```bash
% sed -e "/^ \* /s,\([a-z]*/#[0-9]*\),<a href="https://github.com/owncloud/issue/\1">#\1</a></li>," -e "s,^ \* ,<li>,"
```

**Comment by guruz** [comment]
@danimo has a regexp at least for the client repo.

**Comment by PVince81** [comment]
@guruz yes, it was a vim regexp.

**Comment by hurradieweltgehtunter** [comment]
Issues references website before relaunch. I'm closing this. There is a changelog discussion going on here: #1354
