### ISSUE TITLE
Owncloud.org is not updating twitter feed and forum latests comments.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/owncloud.org#1056]
Web owncloud.org is not updating twitter feed and forum latests comments.

![screen shot 2016-09-20 at 13 41 55](https://cloud.githubusercontent.com/assets/9048796/18668834/1ef74dde-7f38-11e6-8178-8d8fcd985b09.png)

**Comment by Kawohl** [comment]
Noticed!

Had to do with the migration, will fix this afternoon.


Best John

**Comment by Kawohl** [comment]
Fixed
