### ISSUE TITLE
owncloud.org/blog Page is missing

### ISSUE THREAD

**Issue by Kawohl** [owncloud/owncloud.org#1060]
When you got to owncloud.org/blog 

This Page is missing.
@agssl can you check please?

Thank you! 
John

**Comment by guruz** [comment]
FYI @msrex

**Comment by msrex** [comment]
I was never involved with the website. This is more Achim's area of 
expertise.

**Comment by RealRancor** [comment]
I think it would be really great to get this back. Especially as blogposts like:

https://owncloud.org/blog/introducing-owncloud-security-lead-peter-prochaska/

are completely missing. The blogpost mentioned there is not even showing up at https://owncloud.org/news/ or at "ownCloud News" at the startpage of owncloud.org

**Comment by PVince81** [comment]
cc @stkjj

**Comment by Prakharsvnit** [comment]
@PVince81 Hi, I would like to work on issue mentioned here . Moreover, i think the design of webpage at https://owncloud.org/blogfeed/ can be improved.

**Comment by stkjj** [comment]
it's already work in progress. We'll have a complete new planet owncloud

**Comment by Prakharsvnit** [comment]
@stkjj That's great.Is there any way i can contribute,i would love to do that.I have good front-end knowledge of html,css,javascipt and its frameworks.

**Comment by Kawohl** [comment]
@stkjj any news? Where is this developed?

**Comment by Kawohl** [comment]
all links to news now.
