### ISSUE TITLE
Test pilot page is deprecated

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/owncloud.org#1062]
https://doc.owncloud.org/server/9.2/developer_manual/testing/index.html

It has former emails and perhaps an old description.

**Comment by guruz** [comment]
Something for carlaschroder ?

**Comment by guruz** [comment]
@carlaschroder

**Comment by carlaschroder** [comment]
@guruz Thanks, I'll remove it. Which ownCloud releases does this apply to, 9.2 only?

**Comment by guruz** [comment]
@settermjd  :)

**Comment by Prakharsvnit** [comment]
PR here [#2887](https://github.com/owncloud/documentation/pull/2887)
