### ISSUE TITLE
Links to Linux desktop client testpilot nightlies seems bogus?

### ISSUE THREAD

**Issue by guruz** [owncloud/owncloud.org#1068]
On https://owncloud.org/install/#testing-development we link on lower right to ownCloud testpilot Linux packages

This leads me to:
https://software.opensuse.org/download/package?project=isv:ownCloud:community:testing&package=testpilotcloud-client

Which seems to be stuck at 2.2.0 packages. What's wrong?

**Comment by dragotin** [comment]
The package was never updated in the past, which you do through jenkins. Should be fixed now.
