### ISSUE TITLE
https://owncloud.org/history/ should be updated

### ISSUE THREAD

**Issue by davitol** [owncloud/owncloud.org#1072]
https://owncloud.org/history/

There is no info added to the timeline since oC 9.0 release. There have been several news to add there. (o.C 9.1, desktop 2.2.X, ownCloud Conference 2016... )
OOTH maybe it should be update the info related to ownCloud Inc written there.

**Comment by Kawohl** [comment]
@stkjj FYI

**Comment by hurradieweltgehtunter** [comment]
Push. After relaunch /history is missing atm. We need to setup this page and keep it updated.

**Comment by davitol** [comment]
404. I guess we do not want to keep this section, so let's close this ticket
