### ISSUE TITLE
Add links to ASC and MD5 files on the download popup

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud.org#1074]
The installation popup https://owncloud.org/install/#edition says that one can verify the GPG or MD5 of an archive, but doesn't provide any links to these.
The user needs to guess that they need to append ".md5" or ".asc" to the download link to get those.

It would be good to add additional links to the release-specific signature files.

**Comment by PVince81** [comment]
also ".sha256"

**Comment by PVince81** [comment]
https://github.com/owncloud/owncloud.org/blob/master/install-instructions.php#L64

**Comment by RealRancor** [comment]
Seems that was "refactored" away in https://github.com/owncloud/owncloud.org/pull/1041

**Comment by hurradieweltgehtunter** [comment]
Closing this because it references the old page before relaunch.
