### ISSUE TITLE
Provide trustful way to install the client on Debian 8

### ISSUE THREAD

**Issue by Giszmo** [owncloud/owncloud.org#1076]
Currently, the [https download link](https://owncloud.org/install/#install-clients) sends me to [https opensuse](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client) which then elaborates to download both the deb and the `Release.key` from http with no attribution to who's key it is. The key file last being updated yesterday further hurts my trust.

Ideally this should work out of the box from the debian repository but with https and a key signed by people I can verify it would at least be possible to make sure it's not being messed with on a per downloader basis.
#1075 and #845 might be related.

**Comment by Kawohl** [comment]
We are updating the Keys to fix some issues. No reason to be worried. 
https://central.owncloud.org/t/owncloud-repositories-got-a-new-pgp-key/2637

Maybe @crrodriguez has an idea or can be any help?

**Comment by Giszmo** [comment]
With all due respect, there is a reason to be worried. There is no key chain provided and whoever controls the network of a victim can provide whatever software, signed with whatever key to that victim known to want to upgrade its owncloud client. Which part of my assessment is wrong?

**Comment by crrodriguez** [comment]
@Giszmo The release.key file is generated by the openSUSE buildservice, in an automated fashion, there is no person or organization to which this key belongs to (it belongs to the isv:owncloud subproject only) Under the hood, there is network a isolated/restricted host who creates it and signs packages with this key.

**Comment by Giszmo** [comment]
Fair enough. So how do I verify I got served the same `.deb` and `.key` file as others and did not run victim of a MITM attack? Is there at least some https list of key fingerprints to verify?

**Comment by RealRancor** [comment]
"Upstream" bugreport: https://github.com/openSUSE/software-o-o/issues/108

**Comment by Giszmo** [comment]
What's to stop the owncloud team to also host the release key on their main site (and document how to verify it)? Wouldn't that be helpful even if openSUSE had the key hosted via https, for the case of openSUSE getting hacked? Looks like a jackpot to hack if that's how many projects distribute their binaries.

**Comment by RealRancor** [comment]
I doubt that much people would have a look at the main site for the key. So it would be a real benefit if they provide it via https in the first step.

However the main page of the server already has the OBS key via https:

> Clicking on “Continue” will forward you to the ownCloud download page, which hosts the repositories for all distributions. Further instructions on how to install ownCloud for your distribution are also provided there. Here is the key used to sign our packages.

-> https://owncloud.org/install/#edition

so it might be useful to do the same for the client download.

**Comment by RealRancor** [comment]
As stuff like this takes ages in the ownCloud world one mostly needs to take action. Here is a PR to fix this issue: https://github.com/owncloud/owncloud.org/pull/1079

**Comment by Kawohl** [comment]
@crrodriguez @jnweiger
