### ISSUE TITLE
Features page is showing up blank

### ISSUE THREAD

**Issue by isleshocky77** [owncloud/owncloud.org#1085]
The page for Feature (https://owncloud.org/features/) is returning blank. This is the page which is linked from the menus for "Features" as well as from Google Search Results for "Features".

![screenshot from 2016-10-22 19 39 00](https://cloud.githubusercontent.com/assets/361586/19623207/33216996-988f-11e6-9b13-b34807b726b9.png)

**Comment by Kawohl** [comment]
Is resolved, /not reproducable. There was some server maintenance this weekend
