### ISSUE TITLE
Remove LibreOffice Online app from appstore

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#1095]
As seen in the comments of the page at https://apps.owncloud.com/content/show.php/LibreOffice+Online?content=174455 people are still trying to install that app.

However the readme of the github repos clearly says:

> This repository is obsolete, please use upstream RichDocuments application.
> https://github.com/COMU/libreonline-owncloud/blob/master/README.md

I think it might make sense to remove that app from the appstore to prevent confusion and issues with two different apps.

cc @farukuzun

**Comment by RealRancor** [comment]
Grrml. wrong repo. Sorry.

**Comment by farukuzun** [comment]
Just saw it, i think it's already removed, if not let me now please :)

**Comment by RealRancor** [comment]
Yupp, it was removed after i've posted in the correct repo: https://github.com/owncloud/appstore-issues/issues/75#issuecomment-259920906

Still thanks for having a look here :-)
