### ISSUE TITLE
owncloud.org invalid certificate

### ISSUE THREAD

**Issue by Kawohl** [owncloud/owncloud.org#1107]
Seriously guys! This sucks!

https://owncloud.org/

**Comment by Kawohl** [comment]
![screen shot 2016-11-27 at 09 12 48](https://cloud.githubusercontent.com/assets/12275313/20646746/cc35b476-b481-11e6-8c30-4088b1b4819e.png)

**Comment by draht** [comment]
The cron job could not run, apparently. 
/bin/false is good if you never want to execute anything. 

It's fixed now.
Thanks for reporting this issue!
Roman.

**Comment by Kawohl** [comment]
Thanks!
