### ISSUE TITLE
Email Flood

### ISSUE THREAD

**Issue by bat553** [owncloud/owncloud.org#1109]
Hi ! I have a public cloud and I was victim of a reset password spam. 100 mail in 10 minutes... Can you add a waiting time between requests ? 

PS: Sorry for my English :-/

**Comment by RealRancor** [comment]
@bat553 If you create a new issue here the following is shown:

> Please note this is the issue tracker for the ownCloud homepage at https://www.owncloud.org.
> 
> This issue tracker is NOT the place to ask for support or report issues of ownCloud itself.
Please use https://central.owncloud.org instead.

Please close here and create a new issue at https://github.com/owncloud/core/issues . Make sure that you're filling out the issue template shown there when creating such a new issue.
