### ISSUE TITLE
owncloud 9.0 debian 7

### ISSUE THREAD

**Issue by teadur** [owncloud/owncloud.org#1117]
It seems that owncloud 9.0 repository for debian 7 doesnot seem to contain required debs.
http://download.owncloud.org/download/repositories/9.0/Debian_7.0/all/

**Comment by kdslkdsaldsal** [comment]
@teadur At least now (not sure about the beginning of the year) there are all available packages for Debian 7 provided at the linked repository (only owncloud-files is available for debian oldstable / 7.0).

You can also close this issue as such reports about packages belongs to https://github.com/owncloud/core/issues (the repository here is only for the owncloud.org homepage).
