### ISSUE TITLE
Desktop client's changelog problems

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/owncloud.org#1123]
- [ ] Download links to binaries older than `v2.1.1` are broken (e.g. https://download.owncloud.com/desktop/stable/ownCloud-2.1.0.5683-setup.exe)
- [ ] `v2.2.1` links are not even present in the changelog.
- [ ] All the Linux download links point to the stable version OBS repository

Also, It would be nice to have a delimiter (e.g. horizontal rule), clearly stating from which versions of the client is "deprecated"/have issues with the server: https://doc.owncloud.org/desktop/2.2/introduction.html#introduction:

> Because of various technical issues, desktop sync clients older than 1.7 will not allowed to connect and sync with the ownCloud 8.1+ server. It is highly recommended to keep your client updated.

Note: some package managers, like chocolatey on Windows, rely on this links to offer some [old versions of the client](https://chocolatey.org/packages/owncloud-client/1.7.1.4382) and therefore are unable to install.

**Comment by hurradieweltgehtunter** [comment]
Closing because referencing to old website before relaunch.
