### ISSUE TITLE
link pointing to the wrong location

### ISSUE THREAD

**Issue by Prakharsvnit** [owncloud/owncloud.org#1137]
On clicking at OwnClouder link in a comment section @  https://owncloud.org/blog/owncloud-and-google-summer-of-code/#comment-77440 points  to https://www.na.com.It needs to be changed.

**Comment by PVince81** [comment]
@agssl

**Comment by Prakharsvnit** [comment]
@PVince81 I'm currently working on this issue,it's taking time due to development environment setup, will get back to you asap.

**Comment by Prakharsvnit** [comment]
I successfully setup development environment for owncloud.org website and tried to check the url above.
![screenshot from 2017-02-21 02-25-41](https://cloud.githubusercontent.com/assets/19989448/23141510/2653a12c-f7dd-11e6-941b-ae1cb359ddc6.png).i couldn't load the comment.Is there a way to correct it.

**Comment by tboerger** [comment]
@stkjj is responsible for the owncloud.org website, so I'm pretty sure he can give some hints.

**Comment by Prakharsvnit** [comment]
@stkjj am I missing something here how to load comments.
Or this webpage is old and will be removed .

**Comment by stkjj** [comment]
@Prakharsvnit indeed this repo is only as long alive til the new owncloud.org page is released. If you want to contribute I suggest to head over to https://github.com/owncloud/2017owncloud.org. Intention is to split up content and theming - just as WordPress is thought. Presently a.m. theme is just the beginning of this separation process and reflects actual design. Additional templates still have to be build.

**Comment by Prakharsvnit** [comment]
@stkjj I cloned the repo directly in /var/www/html/wp-content/themes but there was no content.xml file to import according to instructions [here](https://github.com/owncloud/owncloud.org#setup-of-a-local-development-environment). I pointed my browser address to localhost it showed me this:
![screenshot from 2017-03-08 14-04-06](https://cloud.githubusercontent.com/assets/19989448/23696260/f49de2c2-0408-11e7-8feb-019bb1ca47b9.png)
Am i doing something wrong here?

**Comment by Kawohl** [comment]
i fixed the comment,
initial issue closed.
