### ISSUE TITLE
Cannot login local user when LDAP server not accessible

### ISSUE THREAD

**Issue by NothingCtrl** [owncloud/owncloud.org#1150]
When LDAP server not accessible, local user cannot login (example: Admin), I think it should be affect ldap user only.
Owncloud version: 9.1.4

**Comment by phil-davis** [comment]
This is the repository for the web site code. You should log issues with the ownCloud server (and its webGUI) in the repo https://github.com/owncloud/core
Search there to see if the issue is reported, otherwise add the issue using the issue template provided there.
