### ISSUE TITLE
How are links generated out of php files?

### ISSUE THREAD

**Issue by lefherz** [owncloud/owncloud.org#1179]
Hi all,

I am reworking https://staging.owncloud.org/events/ atm, and want to introduce a new event archive, as asked for by @stkjj. I created a new page for this, page-events-archive.php.
Unfortunately I can't figure out how its URL is generated. I want to link to it from page-events.php, how do I do it? href="page-events-archive.php doesn't work, neither does href="/events-archive/" or href="/events/archive".

I have no clue about wordpress, so maybe someone of you can just fix this small link. Until then I have removed the link to the archive with this workaround. Just take a look into my pull request: https://github.com/owncloud/owncloud.org/pull/1178

It is not urgent, with the above pull request the status quo is just that you can't see the events from 2015-2016.

lg Emil

**Comment by lefherz** [comment]
I heard that you have to create an empty file which is then filled by the theme. I still don't understand how this works exactly, but as someone else took care of the problem, i don't need to know either. Therefore I now close this issue :))

**Comment by jnweiger** [comment]
Did you find a solution?

**Comment by jnweiger** [comment]
In case you find the solution, please document it here for future reference.

**Comment by lefherz** [comment]
@stkjj found it :) maybe he wants to share his path? https://xkcd.com/979/
