### ISSUE TITLE
Old apps page does not redirect

### ISSUE THREAD

**Issue by Apophenia** [owncloud/owncloud.org#118]
http://owncloud.org/features/apps/ does not redirect to another page, despite being one of the first pages that surfaces when running searches for "ownCloud Apps."

**Comment by jospoortvliet** [comment]
@tomneedham I think this should just redirect to apps.owncloud.com - but I dunno how to make redirects... could you try to do this if you can find a minute??!?!

**Comment by Prakharsvnit** [comment]
@jospoortvliet for redirecting to apps.owncloud.com,you need to add 
`Redirect 301 /features/apps/ https://app.owncloud.com/` 
under `RewriteEngine On`  in .htaccess file.

Alternatively, you can install Redirection plugin activate it,and change the source url of page [http://owncloud.org/features/apps/](url) to [https://apps.owncloud.com](url)

**Comment by Kawohl** [comment]
I guess we can close this. new place anyway  marketplace.owncloud.com
