### ISSUE TITLE
Broken source download link

### ISSUE THREAD

**Issue by jiyyt** [owncloud/owncloud.org#1183]
The release 2.3.1 download link from the [desktop client page](https://owncloud.org/changelog/desktop/) goes to https://download.owncloud.com/desktop/testing/owncloudclient-2.3.1.tar.xz1, which doesn't exist. All I see there are release candidates.

**Comment by jnweiger** [comment]
This should end in tar.xz, not tar.xz1 -- But I cannot find the position of that link. 
@lefherz  is it already fixed?

**Comment by lefherz** [comment]
there are no testing DL links on the website, only stable. at least on the desktop client page you linked. also the malicious URL you mentioned is not in the source code of the page. I really cant see where you found that broken link...

**Comment by jnweiger** [comment]
These links come from strings.php -- this is a fast changing config file. If you can no longer find it, it is probably already fixed.
