### ISSUE TITLE
Packages links for ownCloud X are 'tagged' as 9.2.0 for all OS

### ISSUE THREAD

**Issue by davitol** [owncloud/owncloud.org#1185]
![screen shot 2017-04-19 at 09 28 21](https://cloud.githubusercontent.com/assets/10596560/25168846/551d5bee-24e5-11e7-9f1d-8e5dbf73c00d.png)
![screen shot 2017-04-19 at 09 28 33](https://cloud.githubusercontent.com/assets/10596560/25168857/5b149030-24e5-11e7-986e-2cabfc7afc5c.png)

@jw @crrodriguez

**Comment by Kawohl** [comment]
@jw @crrodriguez if you try to install from owncloud.org the pointer is still to 9.1.5

**Comment by Kawohl** [comment]
@crrodriguez any news? this seems really wrong

**Comment by Kawohl** [comment]
@crrodriguez still ??

**Comment by davitol** [comment]
@Kawohl @crrodriguez Yes, it is still an issue

**Comment by hurradieweltgehtunter** [comment]
Should be fixed after relaunch right?
If not, please open  anew issue and let me know.
Thx
