### ISSUE TITLE
testpilot client visibility 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/owncloud.org#1192]
We have a shiny new testpilotcloud-client-2.3.2~RC1 release today. 
This is the prefered way to try out the new client without interfering with a running owncloud-client.

https://owncloud.org/ -> 'Download' leads to https://owncloud.org/install/
There I'd look into either 'Desktop Clients' or 'Testing Packages' but neither one links to the Testpilot client.

The only way to see instructions and links for the Testpilot client is found under 'Contribute' -> 'Test ownCloud' "Download test archives and packages from https://owncloud.org/install/#testing-development."

The client Changelog for the 2.3.2~RC1 release should be linked on https://owncloud.org/install/#testing-development too.
Currently I can only find it in https://owncloud.org/install/#install-clients under the name '2.3.1' (Changelog) (where I would not look for 2.3.2 release candidate changes...)

**Comment by guruz** [comment]
FYI I won't be able to do this.. but I agree, we should always have both ownCloud and testpilot be downloadable..

**Comment by jnweiger** [comment]
@michaelstingl @lefherz this is what we discussed this morning.

**Comment by Kawohl** [comment]
fixed with new release.

**Comment by guruz** [comment]
That looks definitely better now with the new website.
