### ISSUE TITLE
Tabs broken in "Mobile clients" modal dialog on download page

### ISSUE THREAD

**Issue by dschmidt** [owncloud/owncloud.org#1215]
When you click on the "Mobile clients" button here https://owncloud.org/install/#, the desktop client tab in the modal dialog is non functional.
when you click on desktop clients straight away, both tabs work as expected.

I see this in Chromium 57 fwiw.

**Comment by Kawohl** [comment]
@dschmidt nice find!
@agssl could you please take a look?

**Comment by Kawohl** [comment]
seems fixed
