### ISSUE TITLE
Notes/updates to the "Good bye apps.owncloud.com" blogpost

### ISSUE THREAD

**Issue by kdslkdsaldsal** [owncloud/owncloud.org#1245]
Hi *,

thanks for the blog post on how to use the new marketplace in older oC versions at:

https://owncloud.org/blog/good-bye-apps-owncloud-com/

Just some notes:

1. Are there any reasons why this blogopost wasn't announced at central nor at the mailinglist?
Reason: The blogpost is already hidden on the startpage https://owncloud.org/ and only shown when browsing to https://owncloud.org/news/ and scrolling down and skipping later blogposts.

2. The code block for the config.php entry currently looks like the following when copy'n'pasting

```
‘appstoreurl‘ => ‘https://marketplace.owncloud.com/api/v0‘,
```

I think the quotes should be rather:

```
'appstoreurl' => 'https://marketplace.owncloud.com/api/v0',
```

3. You could note, that people needs to disable and uninstall existing apps from the old appstore like e.g. `calendar` or `contacts` first before they can install and enable the newer versions from the marketplace. If not uninstalling those you will get an "app directory already exists" message.

**Comment by PVince81** [comment]
@emil

**Comment by PVince81** [comment]
@Kawohl

**Comment by Kawohl** [comment]
Thank you! Fixed it.

**Comment by Kawohl** [comment]
Ah wee need to make this sticky somehow. @kremer can you take a lokk please?

**Comment by lefherz** [comment]
@stkjj

**Comment by stkjj** [comment]
can add "sticky" to the post, but ownCloud Planet - based on contribook - does not respect this. As we have no separate blog-page (yet) showing a list of our posts, the sticky-flag is completely out of order by now. Will be fixed in the new oc.org site

**Comment by Kawohl** [comment]
@kdslkdsaldsal thanks again for reporting this i hope this all gets better once the new ownCloud.org is deployed i added a page https://owncloud.org/good-bye-appstore-welcome-marketplace/ with the marketplace content. But i am not sure where to link or to put it.
