### ISSUE TITLE
Add electronic mechanism to sign contrib agreement ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/owncloud.org#1263]
ref https://owncloud.org/contribute/agreement/

We also allow an electronic way of signing the contrib agreement by using https://cla-assistant.io/

A new contributor can sign the cla within github.

if you need more information please let me know.

**Comment by DeepDiver1975** [comment]
TBH: this is the only way ;-)

**Comment by DeepDiver1975** [comment]
This is also wrong - multiple repos require the cla

```
Does this mean that everybody who wants to contribute to ownCloud has to sign this agreement?

No. Only the ownCloud core repository is covered by this contributor agreement. ownCloud is build out of a lot of small modules called apps. We don't require a contributor agreement for the apps, only for the core, the desktop clients and android.

**Comment by Kawohl** [comment]
@Deep Diver do you have a list?

**Comment by DeepDiver1975** [comment]
> do you have a list?

this changes over time ...

![bildschirmfoto von 2017-08-22 11-38-37](https://user-images.githubusercontent.com/1005065/29559128-7d225f94-872e-11e7-8ee9-ae9098997f72.png)

**Comment by Kawohl** [comment]
Merci!

**Comment by michaelstingl** [comment]
@hodyroff Should we handle the [iOS Addendum](https://owncloud.org/wp-content/themes/owncloudorgnew/assets/files/Addendum_iOS.pdf) in the CLA tool as well? @DeepDiver1975 Is it possible to have an extended version for iOS?

**Comment by DeepDiver1975** [comment]
Possible

**Comment by Kawohl** [comment]
imo  not needed anymore.
