### ISSUE TITLE
 https://doc.owncloud.org/server/10.0/developer_manual/testing/ needs rework

### ISSUE THREAD

**Issue by Kawohl** [owncloud/owncloud.org#1264]
As above wrong information all around.

https://doc.owncloud.org/server/10.0/developer_manual/testing/ needs rework

**Comment by Kawohl** [comment]
@lefherz @stkjj

**Comment by lefherz** [comment]
Hm, the link is from doc.owncloud.org and technically belongs in this issue-tracker, I think: https://github.com/owncloud/documentation/issues

Or do you mean another page maybe?

**Comment by Kawohl** [comment]
Thanks will reopen in docs.

**Comment by Kawohl** [comment]
https://github.com/owncloud/documentation/issues/3324
