### ISSUE TITLE
owncloud.org/install link seems broken

### ISSUE THREAD

**Issue by alexkuznetsov** [owncloud/owncloud.org#1275]
Hi!

The link from title opens blank window, it seems like a PHP error (or something similar).
And it is a little bit difficult to download your software :) Please, check your site and fix it.

And thank you for all your work with ownCloud, it is great software!

**Comment by Kawohl** [comment]
hey @alexkuznetsov could you please be a bit more specific about the link or provide a sreenshot with an annotation?

**Comment by alexkuznetsov** [comment]
hi @Kawohl , i was talking about https://owncloud.org/install
Now the page opens correct. When i wrote about this issue, the page was blank - just simple white page without any html markup.

**Comment by alexkuznetsov** [comment]
I think the problem can be closed as not relevant, now everything is working fine
