### ISSUE TITLE
ownCloud Newsletter – Subscribe Button commented out

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/owncloud.org#1279]
https://owncloud.org/newsletter/

![newsletter___owncloud_org](https://user-images.githubusercontent.com/214010/30520630-fc1db324-9bb1-11e7-9090-5362963bdf92.png)

How can I subscribe to the owncloud.org newsletter?

**Comment by psinghal20** [comment]
Hey, is anybody still working on it? I would like to work on this issue. Also, I guess the issue is just of the commented out subscribe button, right?. The button seemed to work perfectly when I corrected it in the browser.

**Comment by Kawohl** [comment]
subscribe works with new page.
