### ISSUE TITLE
wrong version shown in the text in stable channel at owncloud.org

### ISSUE THREAD

**Issue by davitol** [owncloud/owncloud.org#1334]
https://owncloud.org/release-channels/      this link shows that the current stable version is 10.0.0 instead of 10.0.4

![screen shot 2017-12-11 at 10 07 15](https://user-images.githubusercontent.com/10596560/33824064-6a0fbc18-de5d-11e7-91db-9da3ef720aa0.png)

The tarball is 10.0.4, the only bug is the text shown

**Comment by Kawohl** [comment]
will be fixed with relaunch
