### ISSUE TITLE
[relaunch] beta links

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud.org#1337]
I see "fresh" and "production" channels for server and "technical preview".

Would be good to also have "beta" once we have betas for 10.0.5.

**Comment by hurradieweltgehtunter** [comment]
I was told that tech preview contains alphas, betas and RC's and there will be no alpha parallel to a beta or the other way round.

**Comment by hurradieweltgehtunter** [comment]
All download resources are dummies atm. Michael and Felix sent me an email with current download links yesterday. I did not yet had the time to insert them but this will be done asap.

**Comment by hurradieweltgehtunter** [comment]
download links are updated
