### ISSUE TITLE
[relaunch] web preview need better image and title

### ISSUE THREAD

**Issue by tomneedham** [owncloud/owncloud.org#1338]
![screen shot 2017-12-14 at 16 42 54](https://user-images.githubusercontent.com/660805/34003783-158425f6-e0ee-11e7-8158-2806a61d846f.png)

**Comment by tomneedham** [comment]
https://developers.facebook.com/tools/debug/sharing/

**Comment by tomneedham** [comment]
So I can tweet / share this sexy thang ;)

**Comment by hurradieweltgehtunter** [comment]
You're absolutely right. @Kawohl is currently working on the SEO implementations of pages and posts

**Comment by hurradieweltgehtunter** [comment]
![image](https://user-images.githubusercontent.com/16665512/34017535-6b9249fe-e126-11e7-9fe2-7f2c1bbb1e0a.png)

Cool enough? :)
Also check out the other pages:
Download:
![image](https://user-images.githubusercontent.com/16665512/34017567-86f7af5e-e126-11e7-83b8-b1a971facaf4.png)

Features:
![image](https://user-images.githubusercontent.com/16665512/34017577-9892c712-e126-11e7-977a-e66ff3b48105.png)

Community:
![image](https://user-images.githubusercontent.com/16665512/34017661-e91486b2-e126-11e7-85c1-976e03b7dd1a.png)

News:
![image](https://user-images.githubusercontent.com/16665512/34017680-fa7b741a-e126-11e7-9398-70d67958b3cc.png)
