### ISSUE TITLE
Switch community image under https://dev2.owncloud.org/features/

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/owncloud.org#1340]
In my opinion, people look like they're going to a boring concert. I miss a bit the enthusiasm for the "project".

https://dev2.owncloud.org/wp-content/uploads/2017/11/owncloud-community-driven.jpg

**Comment by hurradieweltgehtunter** [comment]
Like this one better?
Thanks for noticing
![image](https://user-images.githubusercontent.com/16665512/34017957-1df4d728-e128-11e7-9376-f39e26613c6a.png)
