### ISSUE TITLE
Security section is not updated

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/owncloud.org#1342]
For example we can see:

![screen shot 2017-12-15 at 09 19 17](https://user-images.githubusercontent.com/9048796/34033096-24720372-e179-11e7-9176-19944f444250.png)

Last server released is 10.0.4.

**Comment by hurradieweltgehtunter** [comment]
Security Page is maintained by @Peter-Prochaska afaik. I sent him an email to check this page and add missing topics.

**Comment by hurradieweltgehtunter** [comment]
Is updated. Thanks for noticing
