### ISSUE TITLE
Hide 'Devel' and 'User' list from https://mailman.owncloud.org/mailman/listinfo/ ? (Don't delete the list)

### ISSUE THREAD

**Issue by guruz** [owncloud/owncloud.org#1345]
This is directly reachable with the ```Mailing List``` link at the footer.

But we want people to use central.owncloud.org

**Comment by hurradieweltgehtunter** [comment]
@Kawohl who can change the mailman page?

**Comment by Kawohl** [comment]
No idea, @jnweiger probably will try to get acess today.

**Comment by jnweiger** [comment]
Please send a ticket to sysadmin@owncloud.com, I probably will try to not touch mailman today :-)

**Comment by Kawohl** [comment]
Ticket opened,

**Comment by Kawohl** [comment]
Done thanks to @mrlinux1

**Comment by guruz** [comment]
merci..
