### ISSUE TITLE
German title on the default 404 page 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/owncloud.org#1350]
I tried to access https://owncloud.org/team (404 page) and everything on the page is in English but the:

```
<title>Seite wurde nicht gefunden. - ownCloud</title>
```

**Comment by hurradieweltgehtunter** [comment]
This is indeed bad and surprisingly really hard to fix o.0 
I'm on it.
Thx for noticing.

**Comment by hurradieweltgehtunter** [comment]
stupid hidden form box. But fixed.
Thx for noticing.
