### ISSUE TITLE
Hosting Partners Page improvements

### ISSUE THREAD

**Issue by lefherz** [owncloud/owncloud.org#1352]
You can't yet apply more than one Filter on the Hosting Partners Page.
More possible filters could be:
* Pricing starts at

You can't yet apply for becoming a Hosting Partner, the page doesn't exist yet.

**Comment by Kawohl** [comment]
imo unmaintainable. Will close. Please reopen if you have other propositions.

**Comment by lefherz** [comment]
Okay, then we don't include "Pricing starts at", but still there are 2 points left:

* you can't yet apply two filters simultaneously, to e.g. see everyone who is "best for consumers" and offers "free plans"
* in the apply form you can't yet specify if you offer "free plans", are "best for consumers", and/or "best for organizations". Checkboxes would be appropriate for those options.

**Comment by hurradieweltgehtunter** [comment]
ok I see you point. Shoudn't be a big deal but no prio rn.

**Comment by hurradieweltgehtunter** [comment]
oops. closed it by accident.
