### ISSUE TITLE
CSS <b> is broken

### ISSUE THREAD

**Issue by lefherz** [owncloud/owncloud.org#1353]
the bold tag in the css seems to be broken.

Example: this interview, where the questions should be bold (and are so in the edit backend): https://owncloud.org/news/schabi-and-owncloud-a-contributors-story/

**Comment by hurradieweltgehtunter** [comment]
done

**Comment by lefherz** [comment]
unfortunately, <strong> is still broken. And strong is what you get if you want to write bold in the GUI editor, so we should fix it. Right now it is necessary to edit <strong> -> <b> in the text editor.

**Comment by hurradieweltgehtunter** [comment]
i just went by the topic title. sorry.
Added bold texts to <strong> elements too.
