### ISSUE TITLE
general changelog process

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/owncloud.org#1354]
We should create an unified process how to get the changelogs of server, client (and maybe mobile apps too) on the website. RN everyone does it differently which makes it hard for me to scrape and display it on the website. 
Opening this for awareness, we should talk and find a way which makes everyones life easier.
@guruz @michaelstingl @PVince81 @Kawohl @jnweiger 

### website perspective
From the website visitors perspective I think we should view a complete changelog per product (server, client, mobile). To do so there are two possibilities:
- you'll get a login to owncloud.org and edit the changelog manually in wordpress (this option might give you cancer, i know :) )
- You put a file on github somewhere in the project which contains all changelog information to all versions. It's up to you how you do this but I will only scrape one file. For best results use markdown to structure content.

Please let me know what you think about it.
I know adjustments to used processes are inconvenient but I'm sure we can ease this up by unifying the processes.

### more ideas
- [ ] Add /feed for changelogs

**Comment by michaelstingl** [comment]
We now have changelogs for all platforms in the GH repos:

https://github.com/owncloud/client/blob/master/ChangeLog
https://github.com/owncloud/core/blob/stable10/CHANGELOG.md
https://github.com/owncloud/android/blob/master/CHANGELOG.md
https://github.com/owncloud/ios/blob/master/Changelog.md

@guruz @SamuAlfageme use Markdown format for client changelog too and make issue ID's clickable? (same as server)

**Comment by hurradieweltgehtunter** [comment]
uh that was fast. Thank you!

**Comment by hurradieweltgehtunter** [comment]
Beautiful: https://owncloud.org/changelog/

**Comment by tflidd** [comment]
> Beautiful: https://owncloud.org/changelog/

for the server it shows me only this (as text, it does not load anything):

[load-github id=”changelog-server” url=”https://raw.githubusercontent.com/owncloud/core/stable10/CHANGELOG.md”]

**Comment by guruz** [comment]
Broken for desktop too.
```
[load-github id=”changelog-desktop” url=”https://raw.githubusercontent.com/owncloud/client/master/ChangeLog”]
```

Please for desktop just add those two links:
```
New releases: https://github.com/owncloud/client/releases
All releases: https://raw.githubusercontent.com/owncloud/client/master/ChangeLog
```
(We can think of a better text later, e.g. the latter one does not contain binary/installer links)
