### ISSUE TITLE
@Download: release date format mixed up

### ISSUE THREAD

**Issue by mmattel** [owncloud/owncloud.org#1356]
https://owncloud.org/download/
Just take a look that the date format on ``release date`` is mixed up, examples on the screenshots below.
I propose anyways the format yyyy.mm.dd as standard. This is naturally and reads most easiest. The format used for the tar ball is the worst one...
 
a.) 
![image](https://user-images.githubusercontent.com/3321281/34405176-228da212-ebb2-11e7-8cc1-09bda296f793.png)

b.) 
![image](https://user-images.githubusercontent.com/3321281/34405182-283ee95a-ebb2-11e7-8e36-6f3b6c89e793.png)

**Comment by hurradieweltgehtunter** [comment]
Thx for noticing.
Fixed. Also buttons won't break lines.
