### ISSUE TITLE
Create an imprint

### ISSUE THREAD

**Issue by lefherz** [owncloud/owncloud.org#1358]
We need an imprint to comply with german website law.

**Comment by jnweiger** [comment]
Should the new owncloud.org page has its own imprint, or just a link in the footer to https://owncloud.com/imprint/ ?
I's suggest to put it in the footer, under the 'Privacy policy' entry.

**Comment by hurradieweltgehtunter** [comment]
@hodyroff is this sufficient in legal terms?

**Comment by hurradieweltgehtunter** [comment]
done: https://owncloud.org/imprint/
