### ISSUE TITLE
merge content for version lifetime and downloads

### ISSUE THREAD

**Issue by felixboehm** [owncloud/owncloud.org#1362]
I think it makes sense to have this content maintained on our website.
https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

Also we can add an explanation on the planned release schedule, related to LTS versions:
- 10.0 LTS, spring 2017 - spring 2020
- 11.0 LTS, spring 2019 - spring 2022

The visual key is, there is one your overlapping, allowing testing and planning of an upgrade.

**Comment by Kawohl** [comment]
good point, @hurradieweltgehtunter what do you think? imho we should grab the table from https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule
