### ISSUE TITLE
owncloud.org and owncloud.com download page has different look and feel and content

### ISSUE THREAD

**Issue by mmattel** [owncloud/owncloud.org#1367]
Wouldn´t it be good that owncloud.com redirects to owncloud.org when you press the download button?
![image](https://user-images.githubusercontent.com/3321281/35452983-d642934e-02c8-11e8-9b49-d17fea329332.png)
Instead of maintaining its own page?

Just stumbled over it and it makes no sense to me and confuses.

@PVince81

**Comment by hurradieweltgehtunter** [comment]
You are absolutely right. Might take a little but we are on it right now.
Thanks for the feedback.
