### ISSUE TITLE
Missing MD5s from Download Section

### ISSUE THREAD

**Issue by terrytibbles** [owncloud/owncloud.org#1368]
I just posted this on the [ownCloud forum](https://central.owncloud.org/t/missing-md5s-from-download-section/11738):

The ownCloud website seems to have been re-designed, and any way of verifying the download seems to have disappeared. Is there any way of verifying the download using MD5 or SHA256?

Thanks.

**Comment by DeepDiver1975** [comment]
@hurradieweltgehtunter you can add .asc and .md5 and .sha256 to the archives to access the checksums.

**Comment by hurradieweltgehtunter** [comment]
Checksums are included again. See below the download buttons of server zip and tar. Others will follow if available.
