### ISSUE TITLE
Only the last 10 news articles are accesible

### ISSUE THREAD

**Issue by nasli** [owncloud/owncloud.org#1369]
### Steps to reproduce
1.Go to news section https://owncloud.org/news/
2.Try to go to the eleventh old post blog

### Expected behaviour
When you scrolldown new post blogs are loading automatically or there is a button to go to next page.

### Actual behaviour
It is only possible to access latest 10 post blog

### Browser
Any

**Comment by hurradieweltgehtunter** [comment]
I know about this. It's on my ToDo List. Thanks for noticing

**Comment by hurradieweltgehtunter** [comment]
Implemented endless scroll on home and /news
