### ISSUE TITLE
Remove "Website" option in Comment Form

### ISSUE THREAD

**Issue by lefherz** [owncloud/owncloud.org#1372]
In the current comment form below blog posts, we offer to enter an URL to be displayed. This is mainly used for spam comments - I have never seen that someone uses this for a valid purpose.

If we just remove the option to post the URL of one's homepage, we could save a lot of time at sorting out spam - and wouldn't offend users if we exclude their homepage from their final comment (expectation management).

**Comment by hurradieweltgehtunter** [comment]
Good point. I removed it
