### ISSUE TITLE
Security advisories are broken

### ISSUE THREAD

**Issue by fgeek** [owncloud/owncloud.org#1375]
Previously security advisories could be found from e.g.:

https://owncloud.org/about/security/advisories/oC-SA-2013-018/
https://owncloud.org/security/advisory/?id=oc-sa-2017-004

All old advisory URLs are now broken and latest advisories are in format https://owncloud.org/security/advisories/xss-in-error-page-2/ without any advisory ID.

Why is this? I don't see any good reason for this change if this was done on purpose. Old advisories are linked in lots of places and I can't find information about some of these case at all from your web page.

**Comment by fgeek** [comment]
Ping?

**Comment by hurradieweltgehtunter** [comment]
Thank you for reporting this and sorry for the late response. I'll have a look

**Comment by hurradieweltgehtunter** [comment]
@settermjd have you had a chance to look into the security advisories?

**Comment by fgeek** [comment]
Ping?

**Comment by fgeek** [comment]
@hurradieweltgehtunter Why was this closed? The problem still exists.

**Comment by hurradieweltgehtunter** [comment]
Since we merged our .org and .com websites this repo is obsolete.
Please have a look at https://owncloud.com/security/ for security relevant information.
