### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mdisrail2468** [owncloud/owncloud.org#1378]
Hello Team,

The login feature to leave a Reply at https://owncloud.org/news/when-efforts-pay-off-owncloud-is-nominated-again-for-the-it-storage-insider-award/ is broken. I have tried that with Facebook and if the user is not logined then it prompts the login page but if the user is already logined then it always throws an error (Please find the attached image).

Regards & Thanks,
Mohammed Israil
![owncloud_brokenlink_poc03 jpg](https://user-images.githubusercontent.com/26349077/41613065-2f7bd2da-7412-11e8-9816-573055ec252a.png)

**Comment by mdisrail2468** [comment]
Hello,

Anyone there?

**Comment by hurradieweltgehtunter** [comment]
Sorry for the late answer. Thank you for notifying us about this. I'll have a look

**Comment by hurradieweltgehtunter** [comment]
Comments have been fixed.

**Comment by mdisrail2468** [comment]
Great! I can confirm the fix. Kudos to you. 
Btw, any reward for my effort and work?


Thanks & Regards,
Mohammed Israil

**Comment by hurradieweltgehtunter** [comment]
If I remember correctly a merch package is on its way to you.
Thanks for your input!
