### ISSUE TITLE
Missing SPF Records

### ISSUE THREAD

**Issue by mdisrail2468** [owncloud/owncloud.org#1379]
Hello Team,

There is no TXT record in DNS zone that defines Sender Policy Framework entry for domain http://owncloud.org/. This makes it easy to spoof your e-mail address. I don't know if you relays on third party sites for authenticity but its always a good option to add the records for the main domain.

I just checked for SPF records for the http://owncloud.org/ domain, and there are none. You can validate by testing yourself here: http://www.kitterman.com/spf/validate.html 

```
> SPF record lookup and validation for http://owncloud.org/
> SPF records are published in DNS as TXT records.
> The TXT records found for your domain are:
> Checking to see if there is a valid SPF record.
> No valid SPF record found of either type TXT or type SPF.
``` 

I strongly recommend you to read this article :
https://www.digitalocean.com/community/tutorials/how-to-use-an-spf-record-to-prevent-spoofing-improve-e-mail-reliability

Hope you'll understand the technicality of this report. Waiting for a positive response from your side. And Please, let me know when you have a fix in place. I'll be more than happy to confirm that from my side as well. Additionally, Please let me know if you want me to send a spoofed mail to you.

Thanks & Regards,
Mohammed Israil

![owncloud_spoofing_poc04 jpg](https://user-images.githubusercontent.com/26349077/41619985-df05e214-7425-11e8-8ef4-66478e4d59e3.png)

**Comment by DeepDiver1975** [comment]
This is a know issue and we are working on this. Please use https://hackerone.com/owncloud for reports like this. THX
