### ISSUE TITLE
ownCloud public PGP key expired

### ISSUE THREAD

**Issue by SecTec** [owncloud/owncloud.org#1381]
Hi,

your "ownCloud public PGP key" on your download page has expired.
[ownCloud public PGP key](https://download.owncloud.org/owncloud.asc)

`curl https://download.owncloud.org/owncloud.asc | gpg --import

gpg -k F6978A26
pub   rsa4096 2013-10-14 [SC] [expired: 2018-09-30]
      E3036906AD9F30807351FAC32D5D5E97F6978A26
uid        [ expired ] ownCloud <info@owncloud.com>`

**Comment by mrlinux1** [comment]
This is the key used to sign e.g. the tarballs. It is used on the sign.int.owncloud.com.

I found it at /root/pubkey4.asc.

This key should be renewed by deepdiver or pvince81 on sign.int.owncloud.com.

**Comment by jnweiger** [comment]
Thanks @SecTec for the reminder!
Pushing an extended key to the download mirrors.

**Comment by jnweiger** [comment]
Done. owncloud.asc is valid for another year.
