### ISSUE TITLE
Download links are broken or wrong

### ISSUE THREAD

**Issue by Phyremaster** [owncloud/owncloud.org#1383]
I may have missed a few, but it appears that all download links on https://owncloud.org/download/ result in a 404: not found error (for example: https://attic.owncloud.com/com/desktop/stable/ownCloud-2.5.3.11470.11300.msi shows a page claiming that the web server can't find the file). Either the links are wrong, the download server is broken, or something else. I think this may be causing other problems for server installations; around the same time that I discovered the issue with the links, my server bugged out.

**Comment by hurradieweltgehtunter** [comment]
Thank you for noticing. I'll have a look immediately.

**Comment by guruz** [comment]
> the download server is broken

this one
:/

**Comment by guruz** [comment]
@Phyremaster You can download macOS .pkg and Windows .msi now also at the bottom of https://github.com/owncloud/client/releases/tag/v2.5.3

**Comment by jnweiger** [comment]
All official links at owncloud.org and owncloud.com were fixed last week already. 
A new release 2.5.4 is out.
