### ISSUE TITLE
remove the google captcha at the login

### ISSUE THREAD

**Issue by lefherz** [owncloud/owncloud.org#1384]
Hi,

I suggest to remove the google captcha at the login page. I have several reasons:

1. It is annoying to fill out every time, and interrupts my workflow.
2. It requires me to unblock google's proprietary javascript to continue working.
3. It is only useful against automated bruteforcing and crawlers who try out usual passphrases. This threat model can far easier be mitigated through a fail2ban rule or something similar.

Thanks.

**Comment by hurradieweltgehtunter** [comment]
you mean this:
![image](https://user-images.githubusercontent.com/16665512/55470760-86a1f980-5608-11e9-80e7-14f6648becd2.png)

It's just one click and yes, it's google but it provides an additional step of security. So if there is "only" the "annoying" reason, I'd rather keep this.

**Comment by lefherz** [comment]
No, there is also reason 2 and 3: it requires proprietary google javascript (the company known for the most extensive surveillance apparatus of the world, which deploys their spyware everywhere), and it is the less effective security measure.

The google captcha has been proven to be breakable: https://github.com/ecthros/uncaptcha

Something like fail2ban is a way better measure to prevent automated brute force attacks.
