### ISSUE TITLE
Download links for Linux Clients are broken

### ISSUE THREAD

**Issue by cortho** [owncloud/owncloud.org#1385]
When I click _Install Instructions_ in order to download a Linux client on https://owncloud.org/download/, I am navigated to https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

There, when I choose the option _Grab binary packages directly_  I receive 404 errors for any distribution other than openSUSE.

I am aware, that the packages are not hosted on owncloud.org, but I did not know where I should file this issue.

**Comment by hurradieweltgehtunter** [comment]
Thanks for your notice. (Un-)fortunately I can't reproduce your error. I was able to download every version of the client for every listed OS.

**Comment by cortho** [comment]
Sorry for reopening, definitively does not work:

![Selection_716](https://user-images.githubusercontent.com/28009362/55891072-34d31380-5bb4-11e9-801f-fbe07e357132.png)

![Selection_717](https://user-images.githubusercontent.com/28009362/55891088-3b618b00-5bb4-11e9-97b5-ba730e05b9fa.png)

$ curl "https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/amd64/owncloud-client_2.5.4.11654+oc-515_amd64.deb"
&lt;!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"&gt;
&lt;html&gt;&lt;head&gt;
&lt;title&gt;302 Found&lt;/title&gt;
&lt;/head&gt;&lt;body&gt;
&lt;h1&gt;Found&lt;/h1&gt;
&lt;p&gt;The document has moved &lt;a href="http://widehat.opensuse.org/opensuse/repositories/isv:/ownCloud:/desktop/Debian_9.0/amd64/owncloud-client_2.5.4.11654+oc-515_amd64.deb"&gt;here&lt;/a&gt;.&lt;/p&gt;
&lt;hr&gt;
&lt;address&gt;Apache/2.4.23 (Linux/SUSE) Server at download.opensuse.org Port 443&lt;/address&gt;
&lt;/body&gt;&lt;/html&gt;

$ curl http://widehat.opensuse.org/opensuse/repositories/isv:/ownCloud:/desktop/Debian_9.0/amd64/owncloud-client_2.5.4.11654+oc-515_amd64.deb
&lt;html&gt;
&lt;head&gt;&lt;title&gt;404 Not Found&lt;/title&gt;&lt;/head&gt;
&lt;body bgcolor="white"&gt;
&lt;center&gt;&lt;h1&gt;404 Not Found&lt;/h1&gt;&lt;/center&gt;
&lt;hr&gt;&lt;center&gt;nginx/1.14.2&lt;/center&gt;
&lt;/body&gt;
&lt;/html&gt;

**Comment by hurradieweltgehtunter** [comment]
We checked on different computers now and everybody is able to download the files. 
Also please note that those are SUSE download mirrors so we can't control what's going on there. We try to contact them. Feel free to contact them too.
