### ISSUE TITLE
App development guide link broken

### ISSUE THREAD

**Issue by cortho** [owncloud/owncloud.org#1386]
On https://owncloud.org/help/ the link to the app development guide https://doc.owncloud.org/server/latest/developer_manual/app/ leads to a 404.

Looks like in docs an index document (like at https://doc.owncloud.org/server/10.1/developer_manual/core/ ) is missing.

Alternatively, the link on the help page could be changed to https://doc.owncloud.org/server/10.1/developer_manual/app/introduction.html

**Comment by hurradieweltgehtunter** [comment]
Thank you for reporting. Fixed it.
