### ISSUE TITLE
RSS feed - access denied by Shield plugin

### ISSUE THREAD

**Issue by j-ed** [owncloud/owncloud.org#1391]
Today I realized that I cannot access the RSS feed anymore. Instead the following WordPress error message is shown.

![grafik](https://user-images.githubusercontent.com/2572764/60890690-1d133600-a25c-11e9-8638-e1a8f9136de2.png)

The displayed IP address is related to a server in China and has definitely nothing to do with my access:

![grafik](https://user-images.githubusercontent.com/2572764/60890856-6feced80-a25c-11e9-88ab-2bffce0cb72e.png)

Can someone please check whats going wrong here.

**Comment by hurradieweltgehtunter** [comment]
Thanks for the notice. I'll check this

**Comment by j-ed** [comment]
Today it is working again. The given IP address was definitely not mine, that was the reason why I thought it must be a server side problem.
