### ISSUE TITLE
RSS feed - access denied by Shield plugin

### ISSUE THREAD

**Issue by j-ed** [owncloud/owncloud.org#1394]
At the weekend I realized that I cannot access the RSS feed anymore. Instead the following WordPress error message is shown.

![grafik](https://user-images.githubusercontent.com/2572764/68569569-b34fa680-045e-11ea-9ae6-8af358f4cfad.png)

The displayed IP address is related to a server in Egypt/Africa and has definitely nothing to do with my Internet access in Germany (**My IP address: 84.176.xxx.yyy**):

![grafik](https://user-images.githubusercontent.com/2572764/68569751-33760c00-045f-11ea-972c-530f21a51356.png)

Can someone please check whats going wrong here.

**Comment by hurradieweltgehtunter** [comment]
Thanks for the hint. I'll have a look.

**Comment by j-ed** [comment]
@hurradieweltgehtunter Yes, I waited several days and hoped that a kind of self-healing would take place, but the error is still shown. It is absolutely weird that the block message is referencing to an ip address which is definitely not mine?!
Additionally I'm missing a way to remove the own ip address from that block list. From what I've found on the Internet, I know that such a function exists but it need to be enabled.

**Comment by hurradieweltgehtunter** [comment]
This is indeed a strange behaviour. I'll keep investigating

**Comment by hurradieweltgehtunter** [comment]
This could be a simple server-side caching problem. Please have a look again.

**Comment by j-ed** [comment]
@hurradieweltgehtunter Thank you, whatever you did, solved the problem It is working again without any error being displayed.

**Comment by hurradieweltgehtunter** [comment]
Great to hear :) Thanks again for the notice!
