### ISSUE TITLE
ownCloud PGP key expired

### ISSUE THREAD

**Issue by apicht** [owncloud/owncloud.org#1396]
owncloud.asc has expired:

```
curl -s https://download.owncloud.org/owncloud.asc | gpg

gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2013-10-14 [SC] [expired: 2019-11-19]
      E3036906AD9F30807351FAC32D5D5E97F6978A26
uid           ownCloud <info@owncloud.com>
sub   rsa4096 2013-10-14 [E] [expired: 2019-11-19]
```

**Comment by Tauwasser** [comment]
Still expired in December :(

**Comment by hurradieweltgehtunter** [comment]
@DeepDiver1975 could you help?

**Comment by jnweiger** [comment]
The current key is available from `gpg --recv-keys --keyserver hkp://keys.gnupg.net 2D5D5E97F6978A26`
@hurradieweltgehtunter can you put it on the webservers?

**Comment by hurradieweltgehtunter** [comment]
Thank you @jnweiger 
I will forward it to our website team.

@Tauwasser Could you confirm that you got what you were looking for?

**Comment by jnweiger** [comment]
Key update is on the mirrors, the URL is now in the expiry checker.

**Comment by hurradieweltgehtunter** [comment]
Thank you. Closing the issue now.
