### ISSUE TITLE
Older ownCloud Packages not available for download

### ISSUE THREAD

**Issue by cortho** [owncloud/owncloud.org#1399]
When clicking "Earlier version" at https://owncloud.com/download-server/ I'm redirected to https://owncloud.com/older-versions/#server where only ownCloud X versions are provided.

So it becomes impossible for users to upgrade from e.g. ownCloud 8.0.0 since the required packages are not available. (see upgrade paths at https://doc.owncloud.com/server/admin_manual/maintenance/upgrade.html)

Please handle with high priority since users now are encouraged to download (possibly harmful) packages from unauthorized sites.

Workaround: find required package in https://attic.owncloud.org/community/

**Comment by cortho** [comment]
Why is this closed without any comment? The issue still persists.
How does ownCloud suggest to upgrade from 9.0.8 or even 8.2.10 ?

**Comment by michaelstingl** [comment]
Older versions added:
https://owncloud.com/older-versions/
