### ISSUE TITLE
upgrading-across-skipped-releases does not provide packages

### ISSUE THREAD

**Issue by cortho** [owncloud/owncloud.org#1400]
On https://doc.owncloud.com/server/admin_manual/maintenance/package_upgrade.html#upgrading-across-skipped-releases the last line reads

> You’ll find repositories of previous ownCloud major releases in the  ownCloud Server Changelog.

which currently links to changelog.

There are no repositories of previous ownCloud major releases

**Comment by cortho** [comment]
Issue still not solved

**Comment by hurradieweltgehtunter** [comment]
Conituned in https://github.com/owncloud/docs/issues/3035
Since oc.org does not exist anymore this repo will be archived.
