### ISSUE TITLE
Use Open Sans as typeface

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/owncloud.org#188]
Since we now use Open Sans as typeface for ownCloud, the website and any assets should be done with Open Sans as well.

You can use the code and font files for that from the core: https://github.com/owncloud/core/blob/master/core/css/fonts.css (font files in the font folder. You might need the regular italic cut in addition.)

cc @tomneedham @MariekevC @kelleybrooks @jospoortvliet

**Comment by jancborchardt** [comment]
@jospoortvliet can you add it? As said above, you simply need to do this:

> You can use the code and font files for that from the core: https://github.com/owncloud/core/blob/master/core/css/fonts.css (font files in the font folder. You might need the regular italic cut in addition.)

And then somewhere in the CSS say `body { font-family: "Open Sans"; }`

**Comment by jospoortvliet** [comment]
will put this on my todo then ;-)

**Comment by jospoortvliet** [comment]
Done :trophy:

**Comment by jancborchardt** [comment]
AWESOME!
