### ISSUE TITLE
http://owncloud.org/contribute/ make the apps more visible 

### ISSUE THREAD

**Issue by schiesbn** [owncloud/owncloud.org#219]
At the moment the "Help improve ownCloud" section mentions the possibility to write your own app but beside that it focus on ownCloud core. I think we should advertise the possibility to work on various existing apps more  prominently, especially the apps shipped by default. Also it would be great if this page could point out which apps are short of developers or need a new maintainer.

It is great to have more developers on core but currently we have some really important apps which are developed by 0-3 developers (depending how you count it). That really worries me and I think we should try to improve it by making the apps and the possibility to work on them more visible.

**Comment by jospoortvliet** [comment]
I think this is addressed, if not, re-open and let me know what I can improve.
