### ISSUE TITLE
Removing documentation from website pages

### ISSUE THREAD

**Issue by tomneedham** [owncloud/owncloud.org#27]
@dragotin @danimo 

Am redesigning the layout of the /install page to incorporate the sync clients page (see [here](http://staging.owncloud.org/install/)).

The /sync-clients page doesn't really add any additional information (beside the testing links which I will move across).

The bulk of it is installation documentation in my opinion and should be moved to a more appropriate location which we can link to.

Do we already have installation documentation (like how to install it on mac...)? If not where should this be copied over?

Just had another look over the page and noticed the changelog. I think this should stay on owncloud.org somewhere as its not documentation as such. Agreed?

Thanks :)

**Comment by jospoortvliet** [comment]
Should all be done/addressed...
