### ISSUE TITLE
Repository key for owncloud-client is published using unsafe protocol

### ISSUE THREAD

**Issue by synchrone** [owncloud/owncloud.org#272]
A link for Release.key at OpenSuSE Build Service [installation instructions](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client) for owncloud-client is http-only, and the server does not support https.

It would be a little step to safety to publish the repository key at https://owncloud.org, before advising users do `sudo apt-key add` after a wget using an unsafe protocol.

**Comment by jospoortvliet** [comment]
Key is now available from owncloud.org/install via https.

**Comment by synchrone** [comment]
@jospoortvliet but not on page OBS: http://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud which is misleading.

**Comment by jospoortvliet** [comment]
@synchrone we don't control that page, I'm afraid.

**Comment by FriendFX** [comment]
@jospoortvliet where exactly on the owncloud.org/install site can the Release.key file be found? I agree with @synchrone that the instructions and key files on the openSUSE site are confusing, who put them there?

**Comment by synchrone** [comment]
@FriendFX I'm thinking those are auto-generated by OBS, so the guys don't have an interface to modify that and too reluctant\small to put some pressure on suse.

As for the key - there's fine print over at https://owncloud.org/install/#instructions-server in the Packages tab under "Here you can grab the key used to sign our OBS packages."

Way too unclear for the majority of newcomers, if you ask me, and also nowhere to be found in Desktop Clients section.

We could do a pullrequest for [owncloud/owncloud.org/install-instructions.php](https://github.com/owncloud/owncloud.org/blob/master/install-instructions.php) and fix that

**Comment by FriendFX** [comment]
@synchrone Thanks for the pointers. Before modifying the instructions, I'd like to get it to work though... using the instructions on the openSUSE site (just changed the source of the key file):

    wget https://owncloud.org/owncloud.asc
    apt-key add - < owncloud.asc
    echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/ /' >> /etc/apt/sources.list.d/owncloud-client.list
    apt-get update

This caused the following warning:

    W: GPG error: http://download.opensuse.org  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 977C43A8BA684223

Seems like the key from the secure owncloud.org site doesn't match the openSUSE site? Sorry for my confusion, I am quite new to package management.

**Comment by FriendFX** [comment]
Ah, just saw that I used the wrong key, which I deleted from the `apt-key` database through `apt-key del F6978A26`.

So the first two lines of my instructions look like this now:

    wget https://owncloud.org/wp-content/themes/owncloudorgnew/assets/files/obs-release-signing.gpg
    apt-key add - < obs-release-signing.gpg

With that, `apt-get update` didn't cause any warnings. So I went on to install the ownCloud client:

    apt-get install owncloud-client

which worked nicely now.

**Comment by FriendFX** [comment]
Looks like the link doesn't have the latest version of the key:
```
pub   1024D/BA684223 2012-02-08 [expired: 2016-08-26]
uid                  isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>
```
I see this in my `apt-key list` just after executing the following one-liner:

    wget -qO - https://owncloud.org/wp-content/themes/owncloudorgnew/assets/files/obs-release-signing.gpg  | sudo apt-key add -

I noticed the [KEYEXPIRED issue](https://github.com/owncloud/core/issues/8262), but folks there used the (widely advertised) insecure URLs like http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_14.04/Release.key (which I tried and which shows an expiration date of 2017-04-19).

@synchrone do you know of another place where a secure download of this key can be found?

**Comment by PVince81** [comment]
@owncloud/packaging

**Comment by FriendFX** [comment]
@PVince81 I think this issue should be re-opened?

**Comment by jnweiger** [comment]
We have a new key at opensuse.org -- maybe we also have a new key at our owncloud.org mirrors.. See also https://github.com/owncloud/client/issues/5055 -- If these two keys can be made identical it would be great!

curl -s http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/xUbuntu_16.04/Release.key | gpg -
pub  2048R/557BEFF9 2016-09-25 isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>

**Comment by RealRancor** [comment]
>  but folks there used the (widely advertised) insecure URLs like http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_14.04/Release.key (which I tried and which shows an expiration date of 2017-04-19).

The URL is not under control of the folks here. Sure, a mirror of the key on a SSL protected owncloud.org is an alternative but it would be the best if you ping the people of OpenSUSE OBS that they should move their page to a SSL protected URL.

**Comment by RealRancor** [comment]
Upstream issue: https://github.com/openSUSE/software-o-o/issues/108

@FriendFX https://github.com/owncloud/owncloud.org/pull/1079 updated the pgp keys on the owncloud.org install page.
