### ISSUE TITLE
Add link to the download repos for the older version

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud.org#330]
Someone on IRC was looking for the repo for 6:0 but it is not shown on the website.

When clicking on "Old versions" it goes to the changelog page http://owncloud.org/changelog so I suggest to improve that page to also include a link to http://software.opensuse.org/download/package?project=isv:ownCloud:community:6.0&package=owncloud

Some people need that when upgrading from OC 5 to OC 7, especially now that we explicitly disallow skipping major versions.

@karlitschek @tomneedham

**Comment by jospoortvliet** [comment]
Solved with #473
