### ISSUE TITLE
http://download.owncloud.com/desktop/testing/ - read folder

### ISSUE THREAD

**Issue by mkormendy** [owncloud/owncloud.org#37]
It'd be great to see a "nightly builds" list of sorts for past versions hosted here:

http://download.owncloud.com/desktop/testing/

Maybe just organize clean up the folder and put a +Indexes on the .htaccess?

**Comment by jospoortvliet** [comment]
Why would we post older nightly builds?!?

**Comment by Kawohl** [comment]
@mkormendy i object that. this doesn't make sense for me. Since this issue is so old i will close it. Feel free to reopen if you would like to discuss on this topic.

**Comment by mkormendy** [comment]
This was for a time when ownCloud was less stable and certain nightlies were more stable than others even vs major releases.

This has changed now and major releases have followed a much more rigorous release process and are more stable.

Thanks for closing this.
