### ISSUE TITLE
Provide links to older releases of desktop client in changelog

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#395]
Hi,

this was asked many times by users at the IRC channel and the forums so creating an issue for this.

Please provide the links to older releases of the desktop client at:

https://owncloud.org/changelog/desktop/

analog to the already existing links for core at:

https://owncloud.org/changelog

Currently the only change to get older releases is to extract the file names from the commit logs of: https://github.com/owncloud/owncloud.org/commits/master/strings.php or from a search on google.

Ref: https://github.com/owncloud/owncloud.org/issues/37 for providing links to testing versions

**Comment by jospoortvliet** [comment]
@danimo @tomneedham how can we do that?

**Comment by jospoortvliet** [comment]
@dragotin are you the 'dude' making the changelog? Then - how about adding the download links there from now on...

**Comment by RealRancor** [comment]
Proposal in https://github.com/owncloud/owncloud.org/pull/502

**Comment by RealRancor** [comment]
Closing as #502 was merged.
