### ISSUE TITLE
Broken rewrite http://owncloud.org/dev/

### ISSUE THREAD

**Issue by guruz** [owncloud/owncloud.org#401]
We had this link in https://github.com/owncloud/client/blob/master/CONTRIBUTING.md
It rewrites to http://doc.owncloud.org/server/7.0/developer_manual/app/index.html/ which is 404

**Comment by tomneedham** [comment]
@guruz Can you remove the trailing slash? Then it works just fine. Otherwise I have to poke with the black magic that is the rewrite rules.

**Comment by guruz** [comment]
cheers :)

https://github.com/owncloud/client/commit/9d93642102fcd1a0758101753d428e661e2fc523

**Comment by tomneedham** [comment]
Super thanks
