### ISSUE TITLE
Provide links to older OC server versions (archive)

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud.org#413]
Similar to https://github.com/owncloud/owncloud.org/issues/395 but for the server version.

It was requested here for people who wanted to test upgrading to an older version: https://github.com/owncloud/core/issues/12801#issuecomment-72591111

**Comment by LukasReschke** [comment]
We already link to older versions at https://owncloud.org/changelog – RCs are however not linked.

**Comment by jospoortvliet** [comment]
I think there's little point in linking to old RC's, sorry... In the thread the old tarball was found and indeed, a google search can find it too as it's announced on the ML's too. I would keep it at that.

**Comment by te-online** [comment]
From my perspective, it would be *really* nice, if there was a hint on the download page that **changelog == download links** (just add it in the modal here: https://owncloud.org/install/).

Reason is, I literally found out by using Google and clicking on one of the first hits, that brought me straight to this issue page. Could be a lead I'm not the only one? 😄

**Comment by RealRancor** [comment]
@te-online https://owncloud.org/install/#instructions-server -> Looking for older versions or major releases? -> https://owncloud.org/changelog -> Profit :-)

**Comment by te-online** [comment]
@RealRancor Oh, wow, embarrassing! 😳  

But honestly, maybe it's me or maybe it's the layout suggesting, that below a screenshot there will be no interesting information other than a caption. I've spent more than a few seconds on the screen and even desperately clicked on ”release channels“ before changing my strategy to using Google. 

Anyways, it's there and that's a plus 👍

**Comment by RealRancor** [comment]
@te-online I think improvement suggestions for a better visible placement are always welcome in a new created issue.
