### ISSUE TITLE
FAQ entry: AGPL impact on theming / custom apps

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/owncloud.org#440]
@jospoortvliet This is a question that often comes up. Basically people want to know how AGPL impacts the theming / custom apps and there are floating around tons of different replies based on that in our forum and Co.

An authoritative answer here might help. – Obviously we should not play lawyer here but give some general hints and then refer to the lawyer of their choice for further information? ;-)

(especially often it comes up the question whether a custom logo would have to be AGPL licensed then as well)

**Comment by LukasReschke** [comment]
Feel free to close if this is something that we don't want to have. Thanks :smile:

**Comment by jospoortvliet** [comment]
Fun question, I don't even know the answer myself. The license of apps would have to be AGPL compatible for sure, themes too where it comes to CSS and HTML but I'll be damned if I knew if this impacts logo's and such, too ;-)

@karlitschek you probably know the answers - I'd be happy to then put them in the FAQ :D

**Comment by karlitschek** [comment]
Excellent question. My interpretation is that the AGPL only applies to code. So if non trivial JS code is used that this has to be open sources. But just logos and basic html and css markup not. But I´m not an expert here.
@schiesbn What do you think?

**Comment by jospoortvliet** [comment]
Ping @schiesbn and @jancborchardt as we now have more theming support. Perhaps this can be addressed in the documentation so @carlaschroder

**Comment by carlaschroder** [comment]
Sure, a reference in the theming docs would be good. Maybe a link to the FAQ?

**Comment by jancborchardt** [comment]
Good question. I am not entirely sure and can only assume from Wordpress themes that there is no problem with logos or even proprietary themes. @schiesbn might know more.

**Comment by RealRancor** [comment]
Mhhh, isn't this already documented here:

https://owncloud.org/faq/#modifyowncloud

**Comment by carlaschroder** [comment]
Well I have to agree with @RealRancor :)

**Comment by jospoortvliet** [comment]
Thinking about it, yes, @RealRancor is right. And as @LukasReschke gave permission to close when this was already documented - I will do that now. Yay.
