### ISSUE TITLE
FAQ: Add entry for persons that contact ownCloud about copyright infringements on ownCloud domains

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/owncloud.org#453]
We (security@) just got another mail from some legal department with a huge bunch of boiler plate text about some copyright infringement by an ownCloud user. Obviously we cannot do anything about this except explaining that we don't have any control over ownCloud installations and we are the wrong party to refer to.

Can we have some boilerplate FAQ entry that I can refer such people to?

cc @jospoortvliet

**Comment by LukasReschke** [comment]
Something like:

> **I want to report a legal infringement on an ownCloud instance.**
> ownCloud is an open-source project that can be easily hosted by any person allowing anybody to securely exchange files. If you found a copyright infringement on another domain than *.owncloud.com or *.owncloud.org please don't contact us and use mechanisms such as whois to find the real owner.

**Comment by danimo** [comment]
> **I want to report a legal infringement on a site that mentions to use ownCloud.**

> ownCloud is an open-source project that can be easily hosted by any person allowing anybody to securely exchange files. Neither the ownCloud open source project nor ownCloud Inc assert any legal or technical control over those domains. If you found a copyright infringement on domain other than  owncloud.org or owncloud.com, please try to contact the domain owner. ownCloud has no insight or control over ownCloud instances.
