### ISSUE TITLE
Host/Find Hosting buttons could look better on 320 window width

### ISSUE THREAD

**Issue by xMartin** [owncloud/owncloud.org#455]
![img_4324](https://cloud.githubusercontent.com/assets/112532/6637566/2de9157a-c97c-11e4-993f-ff444cc40cbf.PNG)

**Comment by karlitschek** [comment]
@jospoortvliet @jancborchardt What do you think?

**Comment by jospoortvliet** [comment]
Guess it's a bootstrap thing, we 'just' use their buttons. I can simply use normal buttons, of course...

Not sure if that's worth it, improving this look in this situation making it a little less nice in all others.

But darn, what device has such a tiny screen that it all has to be this big? ;-)

**Comment by jospoortvliet** [comment]
So, I agree it doesn't look great, but I can't fix it. So I worked around it - we no longer have these buttons on the front page. It still isn't perfect but better ;-)

Other pages might still have these buttons but there isn't really anything I can do.
