### ISSUE TITLE
Cannot upgrade on system with files_encryption enabled

### ISSUE THREAD

**Issue by taxilian** [owncloud/owncloud.org#458]
I tried to upgrade to 8.0.2 but it wouldn't upgrade.  I tried doing it from the console and got this:

    [root@cloud owncloud]# sudo -u apache ./occ upgrade
    Turned on maintenance mode
    Checked database schema update
    Updated database
    PHP Fatal error:  Maximum execution time of 3600 seconds exceeded in /var/www/html/owncloud/lib/private/files/view.php on line 859

    Fatal error: Maximum execution time of 3600 seconds exceeded in /var/www/html/owncloud/lib/private/files/view.php on line 859

If I disable files_encryption it will upgrade, but then I can't decrypt my files (it never finishes, doesn't show any indication it made any progress).  I'd be fine with just decrypting all of my files but there doesn't seem to be an easy way to do it.  I actually didn't mean to enable encryption in the first place and had thought I'd disabled it, but apparently not.

Any suggestions? My current thought is to try lengthening the maximum execution time, but I can't even tell if it's doing anything.

**Comment by jospoortvliet** [comment]
Hi,

This seems a bug in ownCloud, ot in our website. Please submit a bug report following the template https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#submitting-issues in the core repo: https://github.com/owncloud/core

Thanks!

**Comment by LukasReschke** [comment]
@taxilian Please see https://owncloud.org/blog/owncloud-8-0-1-snafu/comment-page-1/#comment-58793

**Comment by taxilian** [comment]
Thanks for the info, and sorry it was in the wrong spot.  As an FYI, the
"run from the command line 'cause it will take forever" thing doesn't work
because lib/base.php line 505 sets a script time limit to 3600 seconds,
which means the script times out before it gets far enough to complete.

I changed that and it did eventually finish.

**Comment by jospoortvliet** [comment]
@LukasReschke man has a good point here... How do we deal with that?

**Comment by RealRancor** [comment]
@jospoortvliet 
That should be already fixed in one of the next OC versions: https://github.com/owncloud/core/pull/14783
