### ISSUE TITLE
Log errors "only variables should be passed by reference at ...

### ISSUE THREAD

**Issue by chuckingit** [owncloud/owncloud.org#467]
Hi - i just updated from 8.0.0 to 8.0.2 and am getting some php warnings and error messages in log thus not sure if simple or serious and share as fyi ... 

the log shows entries like this ->

Only variables should be passed by reference at
 /home/my_sever_path_to_owncloud/lib/private/cache/fileglobalgc.php#50 ... 

and like this -> 
{"reqId":"c869d1c0be34f1658f0de874c6c95735","remoteAddr":"50.187.100.103","app":"PHP","message":"Only variables should be passed by reference at \/home\/my_sever_path_to_owncloud\/lib\/private\/cache\/fileglobalgc.php#50","level":3,"time":"2015-03-17T14:15:38-04:00","method":"GET","url":"\/cron.php"}

cordially, chuck scott

**Comment by LukasReschke** [comment]
That's the bug tracker for our website. Can you please reopen this at https://github.com/owncloud/core using the [issue template](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)? THX.
