### ISSUE TITLE
Add links with fixed oc-version to repo-page

### ISSUE THREAD

**Issue by tflidd** [owncloud/owncloud.org#468]
If I choose to install owncloud via repo sources, owncloud.org gives me only the link to the newest OC version: http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/

Some people want to install a certain OC version and should decide on their own when to upgrade to a new version (stable enough, all their 3rd party apps are compatible). For these people, it would be extremely helpful if you provide a link to a certain OC-version, like OC 7.0.x:
````
http://download.opensuse.org/repositories/isv:/ownCloud:/community:/7.0/Debian_7.0/
````

A lot of people are surprised that this is possible! After the problem with the latest upgrades, I think we should provide information about this option or even make it default: For upgrades it's slightly more complicated but people will be more aware of the fact that they are running an upgrade and should perhaps do backups. Normally the upgrade notice appears in OC, in the linked content, we could put the information on how to change sources and also what is going to change and what has to be considered.
I prefer people asking how to change the sources to upgrade to OC 8 than everyone complaining about a broken setup due to an (unwanted?) upgrade.
Also related to: https://github.com/owncloud/owncloud.org/issues/330

**Comment by RealRancor** [comment]
Seems that got fixed by https://github.com/owncloud/owncloud.org/pull/473

**Comment by jospoortvliet** [comment]
Well, it's now visible in the change log. @tflidd do you have any concrete suggestions on where else to note this? If not, let's close this as done.

**Comment by carlaschroder** [comment]
I think we should make older versions easily accessible, for multiple reasons: easy rollbacks, curiosity, testing... I shall write something up for the admin manual.

**Comment by tflidd** [comment]
Great, links to old versions via repo-manager can be found now.

My concern is, the current docs advices the bleeding-edge version of owncloud and don't even give any information of how to follow a more conservative upgrade strategy. Thinking back to the OC 8 upgrade, a lot of people just hit the regular apt-get update/upgrade and killed their setup.
A second point is that especially users of the community version are more likely to use third party apps. Only a few of them are ready when a new upgrade is pushed. So, probably 80% have no interest of upgrading the very first week.
Personally, I would prefer to use fixed sources for one major OC version. When there is a new version, I would show an update message and link it to the manual on how to change the package sources.

**Comment by jospoortvliet** [comment]
@tflidd 
@carlaschroder already promised to take care of the documentation (isn't she awesome?) and the updater app in 8.1 will support choosing a 'stable stream' on top of that. The issue with apps is also being addressed although there will probably always be a bit of a delay. I'm not sure what we can really do to improve that situation other than making our API more stable and reliable, and we are doing that...

I'm closing this as I think we've done the best we could :dash:

**Comment by tflidd** [comment]
Ok for me. Really good to see all the improvements here.
