### ISSUE TITLE
search in documentation failes

### ISSUE THREAD

**Issue by vascotenner** [owncloud/owncloud.org#470]
I tried to search in the documentation via the search box on https://doc.owncloud.org/ . However, no matter what words I search for, there are no results.

Tried words include:
 * exclude
 * ignore
 * directory
 * sharing
 * symlink

**Comment by jospoortvliet** [comment]
Looks like search only works once you've entered one of the manuals (admin, user, developer). So this works:
https://doc.owncloud.org/server/8.0/admin_manual/search.html?q=performance

This does not:
https://doc.owncloud.org/search.html?q=performance

**Comment by jospoortvliet** [comment]
Oh, this should be reported in http://github.com/owncloud/documentation

I have done that: https://github.com/owncloud/documentation/issues/986
