### ISSUE TITLE
new download page doesn't show any version numbers in the overview

### ISSUE THREAD

**Issue by tessus** [owncloud/owncloud.org#478]
The new [download](https://owncloud.org/install/) page looks nice, but you have to click on https://owncloud.org/install/#instructions-server and https://owncloud.org/install/#install-clients to see the current versions.
If you don't want to put the version numbers in the download/install overview, maybe you can create a separate overview page that shows all current versions.
What do you think?

**Comment by jospoortvliet** [comment]
Good point. Fixing...

**Comment by jospoortvliet** [comment]
![android app contributors2](https://cloud.githubusercontent.com/assets/551757/6831622/c79a2a3e-d321-11e4-8561-5a80368b3f90.png)
This kind of works but isn't super - and doesn't work for the client. @tessus any suggestions on how else to show this? one of the @owncloud/designers might have an idea...

**Comment by tessus** [comment]
@jospoortvliet unfortunately I don't.

**Comment by tessus** [comment]
how was it done before the change?

**Comment by jospoortvliet** [comment]
@tessus the old install page simply had way more text in a vertical rather than horizontal layoud and showed it behind the name, like I have done now. But the page was much more colorful so it looked quite ok.

I can make it blue, but not dark blue so it won't fit color-wise in this page. I think it just doesn't fit - the extra click, I'm sure, won't chase anybody away so I think I'll drop this. But let's give the designers some time to come up with a creative solution...

**Comment by tessus** [comment]
I rather meant how the version numbers were retrieved. You said, you couldn't get the version for the Sync clients. I don't really care about design issues. Whether it's blue, green, pink, or just plain text, it's all the same to me. I only care about the information.
Thanks for looking into this.

**Comment by jospoortvliet** [comment]
@tessus well, sure, I can get the version the same way - but where do I put it on the page? That's the problem ;-)

**Comment by tessus** [comment]
I don't understand. Why not next to it?

![screen shot 2015-03-25 at 14 56 49](https://cloud.githubusercontent.com/assets/223439/6832840/4e4346f6-d2ff-11e4-885e-c941b1bf477a.png)

**Comment by jospoortvliet** [comment]
Works for the server - but 'sync 1.8.0' is only true for the desktop client - the mobile clients (both!) have a different release cycle. So 1.8.0 is only correct for 1/3rd of the clients...

I am slightly inclined to put 1.8.0 there anyway, as you mocked up- this looks quite nice and the mobile clients take care of their own updates anyway.

**Comment by jospoortvliet** [comment]
![android app contributors2](https://cloud.githubusercontent.com/assets/551757/6834625/8ce13446-d335-11e4-835c-44bb7ffcfe04.png)
Let's see what the designers think. I'm still not entirely sure about this...

**Comment by jospoortvliet** [comment]
Let's discuss it in #481 ;-)
