### ISSUE TITLE
download/install instructions include unnecessary step

### ISSUE THREAD

**Issue by tessus** [owncloud/owncloud.org#479]
The [download/install](https://owncloud.org/install/#instructions-server) instructions include an unnecessary step:

2) Check package integrity using MD5 (.tar.bz2 / .zip) or SHA256 (.tar.bz2 / .zip)
3) Verify the authenticity via PGP (.tar.bz2 /.zip). The ownCloud GPG key is here.

Step 2 is unnecessary, since GPG verification would fail, if the file integrity was tainted.

**Comment by jospoortvliet** [comment]
True. Yet, I assume many people will do only one of these two and doing an extra check doesn't hurt, so if you don't mind - I'll close this won'tfix.

**Comment by tessus** [comment]
Sure, I just wanted to mention it, since it didn't make any sense to me.

I understand that a lot of people don't use gpg, so step 2 makes sense in that case. But as soon as somebody uses gpg, step 2 becomes obsolete.
