### ISSUE TITLE
Uploaded files or created folders to show owner's username

### ISSUE THREAD

**Issue by m-izaak** [owncloud/owncloud.org#495]
I think there should be a label to show the original owner's file/folder when it is created or uploaded.
Intuitively it should be where the current "Share" label is.

**Comment by jospoortvliet** [comment]
@m-izaak I don't think this is website, related, is it? If not, please file a bug in the appropriate place - I think http://github.com/owncloud/core/issues is what you're looking for ;-)

On the subject of your request, I think - when you upload files, aren't you by definition the original owner? How can there be files (not shared with you) on your ownCloud instance which aren't owned by you?

I don't understand the need for this... As all files are owned by the person logged in unless shared by somebody else (and then you see who shared them).
