### ISSUE TITLE
Add Tech and Me's .vmdk to install site

### ISSUE THREAD

**Issue by enoch85** [owncloud/owncloud.org#503]
@jospoortvliet Idk if it's you that takes care of the ownClouders account on Twitter? 

Anyway, you promised me to link my .vmdk found at https://www.en0ch.se/owncloud_/pre-configured-owncloud-installaton/ on ownClouds install site https://owncloud.org/install/#instructions-server (under images)

Twitter: https://twitter.com/ownClouders/status/583620296088940544

As I see it there are two alternatives.

1. Link the site (with an explanation of "how to") https://www.en0ch.se/owncloud_/pre-configured-owncloud-installaton/
2. Link the shared link. https://en0ch.se/index.php/s/KwJiBfh1SUvrQQs

IMHO I think it's best to link alternative 1, as the shared link may change. Also, the user get´s more information in option 1, rather than just a file in option 2.

## Design

**The text could be something like**
Tech and Me provides a pre-configured ownCloud install with SSL (self-signed) enabled as a start-up script. The VM runs on Ubuntu 14.04 with Apache and MySQL, and is fully configured from start.

**Image link:** http://i.imgur.com/oXdxdcu.jpg

Would be super if you could make this happen soon. :+1:

**Comment by jospoortvliet** [comment]
@enoch85 see #504

**Comment by enoch85** [comment]
Thanks!

**Comment by jospoortvliet** [comment]
done.
