### ISSUE TITLE
Make clear this is conf #2

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/owncloud.org#511]
Currently it seems like we’re doing this for the first time. It would be cool if https://owncloud.org/conf would make it clear that this is already the second year (and basically we had it before as well). So maybe just say »Our annual conference« or so?

To make that more clear, it would be cool to have the group photo from last year displayed on the bottom of the page (put it on the left of the »Thanks« and »Spread the word« sections). There we can also link to pictures and video recordings of last year.

What do you think @jospoortvliet @karlitschek

**Comment by jospoortvliet** [comment]
yeah, perfectly fine idea. Working on it now.

**Comment by jancborchardt** [comment]
That’s why I love you homie ;D

**Comment by jospoortvliet** [comment]
![statistics april 6 2016](https://cloud.githubusercontent.com/assets/551757/7086281/2f065c42-df7f-11e4-9433-31dcf3cf8ce4.png)
![statistics april 6 2016](https://cloud.githubusercontent.com/assets/551757/7086283/30c741f4-df7f-11e4-9aea-607ac563534a.png)
@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
Aaaawesome!

I would just change 2 things:
* remove the white border from the image
* change the title to something more descriptive maybe? Like "Previous year"?

**Comment by jospoortvliet** [comment]
Done, see #512
