### ISSUE TITLE
New contacts groups duplicating

### ISSUE THREAD

**Issue by labasus** [owncloud/owncloud.org#518]
Then trying to input new contact with marked (selected) one of existing groups, the group dropdown menu shows duplicating list of existing groups, and selected group are duplicating.

**Comment by jospoortvliet** [comment]
Sorry, this is the bug tracker for the owncloud.org website, not for any part of ownCloud. Please, see the repositories on https://github.com/owncloud and file feature requests in the right one.

This seems a bug for the contact app on owncloud/contact. Please read https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#submitting-issues before you submit a bug report.
