### ISSUE TITLE
Folder uploads

### ISSUE THREAD

**Issue by labasus** [owncloud/owncloud.org#519]
ownCloud client can do directory uploading hierarchically, but through the WEB still only file uploads?

**Comment by jospoortvliet** [comment]
Sorry, this is the bug tracker for the owncloud.org website, not for any part of ownCloud. Please, see the repositories on https://github.com/owncloud and file feature requests in the right one.

Questions like these you should ask on IRC or the ownCloud forums. In this case I believe this is a limitation of web browsers, not of ownCloud.
