### ISSUE TITLE
Advanced share permissions

### ISSUE THREAD

**Issue by labasus** [owncloud/owncloud.org#520]
Great and more advanced feature for administrators can be flexible overwrite sharing permissions in subfolders.
Sample: 
1level folder - Read only for ALL groups
2level folders - Have WRITE for some group and READ for the others
3level folders - have read for ALL

**Comment by xfguo** [comment]
:+1:

**Comment by jospoortvliet** [comment]
Sorry, this is the bug tracker for the owncloud.org website, not for any part of ownCloud. Please, see the repositories on https://github.com/owncloud and file feature requests in the right one.

I also suggest to try and describe your features more clearly. Features are only added if there is a clear use case - an example of a scenario where a feature is actually helpful, showing how currently something can not or only be done in a complex way but with the feature would be easily possible.

This feature probably belongs in owncloud/core.
