### ISSUE TITLE
Fix Deeplinks on install page

### ISSUE THREAD

**Issue by danimo** [owncloud/owncloud.org#529]
Anchor-based deep links, such as `#desktop`, or `#testing` only put a focus effect on the respective buttons. They should instead open the modals that open if the button gets pressed.

Example: https://owncloud.org/install/#testing

**Comment by jospoortvliet** [comment]
@danimo https://owncloud.org/install/#testing-development works, so does https://owncloud.org/install/#install-clients - I can change those anchors of course, if you want.

**Comment by jospoortvliet** [comment]
I guess this is resolved then...
