### ISSUE TITLE
Add hint to preliminary Changelog of OC server

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#532]
Hi,

quite often it happens that users are asking if a OC version was already released based on the preliminary Changelog available here:

https://owncloud.org/releases/Changelog

Please add a short note to this Changelog that its not a "final Changelog" but just a preliminary one. This saves a lot of confusion if some one is stumbling over this Changelog via google like in:

https://forum.owncloud.org/viewtopic.php?f=31&t=27918
http://owncloud.10557.n7.nabble.com/ownCloud-7-0-3-tp13376p13390.html

This happens for example in the case of the for weeks delayed OC 8.0.3 where the preliminary Changelog says that this version was released on April 6. 2015.

cc @karlitschek

**Comment by LukasReschke** [comment]
:+1:

**Comment by jospoortvliet** [comment]
@karlitschek I don't control that file, do I? I have a changelog.md in our repo but it last refers to ownCloud 6.0.4...

**Comment by jospoortvliet** [comment]
problem solved by a work-around that Frank does ;-)
