### ISSUE TITLE
Remove search form field from main doc index page

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/owncloud.org#533]
The search form on https://doc.owncloud.org/ returns zero results. In contrast, when you enter any of the manuals and do a search you get good results. So what do you think about removing the search form from https://doc.owncloud.org/? (see https://github.com/owncloud/documentation/issues/986)

Yes, I am asking someone else to do it-- I have gazed up the site theme templates and it did make my head spin :)

@jospoortvliet @tomneedham

**Comment by jospoortvliet** [comment]
I spend an hour on it but I can't figure it out either.

**Comment by carlaschroder** [comment]
@tomneedham , can you help?

**Comment by tomneedham** [comment]
@carlaschroder Im slap in the middle of my third year undergrad exams, back with ownCloud in roughly 5 weeks hopefully :)

**Comment by carlaschroder** [comment]
@tomneedham Ok, cool :) So, who else can do this?

**Comment by carlaschroder** [comment]
@jospoortvliet I think I see how to do this. 'Inspect element' in a Web browser identifies the relevant code bits, so I'll poke at it some more.

**Comment by jospoortvliet** [comment]
Sjees, I should've tried that. Shows I'm no web developer. And it's not for not trying, that 'hour' was an understatement... I poured over all the code in the templates, went over the build system and so on and tried a bunch of things. I can remove the search field on ALL pages, just not only on the index :(

**Comment by tomneedham** [comment]
At a guess there needs to be an additional if condition in here to load the box if != index, or something similar: https://github.com/owncloud/documentation/blob/master/_shared_assets/themes/bootstrap/searchbox.html

**Comment by carlaschroder** [comment]
How about let's just put some text in the search box: IF THIS IS THE INDEX PAGE DON'T BOTHER LOL
:trollface:

**Comment by LukasReschke** [comment]
:laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing:

**Comment by carlaschroder** [comment]
thanks @tomneedham, when I have some spare minutes I'll look at that.

**Comment by carlaschroder** [comment]
Closing for https://github.com/owncloud/documentation/issues/2331
