### ISSUE TITLE
Video on /conf needs Flash

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/owncloud.org#542]
@jospoortvliet is it possible to force the embed to use the HTML5 playback?

**Comment by jospoortvliet** [comment]
I don't have the beginnings of a clue. This is most likely a YouTube setting. Best I can do is re-encode the video to a more friendly format and put it as a link somewhere... Is that worth it?

**Comment by LukasReschke** [comment]
It works fine here on my Chrome. Shows it as HTML5. I think it depends whether HTML5 has been checked at https://www.youtube.com/html5?hl=de and if Flash is available. – Forcing HTML5 seems not to be possible anylonger…

**Comment by jancborchardt** [comment]
Ok, nevermind then.
