### ISSUE TITLE
RSS feed for security advisories

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/owncloud.org#547]
There seems to be a first feed implementation for security advisories, which wasn't finished.

https://owncloud.org/security/advisories/feed/

@tomneedham @LukasReschke What is the status here? Can we fix this :P

See 0cb1d924f55eefc75235451205539a9e2a50e595

**Comment by LukasReschke** [comment]
> Can we fix this :P

Sure, "we" go to https://github.com/tomneedham/owncloud-advisory-generator and write a rss output and find out how to link that in Wordpress :see_no_evil:

**Comment by MorrisJobke** [comment]
Okay. Let me have a look :)

**Comment by tomneedham** [comment]
@MorrisJobke */feed is generated by wordpress automatically and is a feed of comments to the page.

**Comment by tomneedham** [comment]
@MorrisJobke There is a rewritten advisory generator that I wrote during the Nurnberg meetup but isn't online yet. Two weeks and I'm done with exams :)

**Comment by MorrisJobke** [comment]
> @MorrisJobke There is a rewritten advisory generator that I wrote during the Nurnberg meetup but isn't online yet. Two weeks and I'm done with exams :)

Okay :) Then I will hand this to you :stuck_out_tongue_closed_eyes: :+1:

**Comment by michaelstingl** [comment]
@tomneedham @MorrisJobke Thanks!

00003115

**Comment by hurradieweltgehtunter** [comment]
up and running after relaunch
