### ISSUE TITLE
https://owncloud.org/theming/ is no more available

### ISSUE THREAD

**Issue by mckayn** [owncloud/owncloud.org#563]
Heya,
do you mind to put a redirect on the link in the title?
Thanks

**Comment by jospoortvliet** [comment]
Where to? I unfortunately can't make redirects, we have to wait for @tomneedham to be available again ;-)

**Comment by mckayn** [comment]
Heya @jospoortvliet,
good question. Typing owncloud theming into google gives back the the tutorials for owncloud 6,7,8 in the 3 first hits. A page that gives the possibility to choose Owncloud 6,7,8 woukd be great under  that url.
Otherwise, just redirect to https://doc.owncloud.org/server/8.0/admin_manual/operations/theming.html :D

**Comment by jospoortvliet** [comment]
Ok, that makes sense... Will see if @tomneedham becomes available again and can help...

**Comment by jospoortvliet** [comment]
So I solved it with a work-around - created the page. It's simple, just linking to the documentation and showing one screenshot - but it'll do.
