### ISSUE TITLE
FAQ: Official statement "oC as a backup solution"

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#564]
Hi,

at the forums we're discussing quite often if oC is a backup solution. From my and some other forums members PoV you shouldn't rely on oC for backups and should do additional backups. The main reason is, if the database and the filesystem at either the server or the client gets corrupted the files are very likely gone on the next sync run.

It could be useful to have an official statement on this at the FAQ.

Cc @karlitschek @jospoortvliet

**Comment by jospoortvliet** [comment]
@RealRancor very good point. Yes, oC is NOT a backup solution - not at all. While a backup app would be awesome to have for ownCloud, for now you have to deal with stuff at a lower level ;-)

How about adding this FAQ item under the technology section:

# can I use ownCloud as a backup solution?

No, ownCloud is absolutely *not* a backup solution. Changes you make in one place are synchronized to other places which means that if you accidentally remove or overwrite a file on your local system, ownCloud will remove it from the server. The *'previous files'* and *'undelete'* functionality of ownCloud is merely meant as a convenience and should never be relied upon as a backup function. Algorithms are in place which clean up 'old files' and thus, changes will get lost over time.

**Comment by RealRancor** [comment]
@jospoortvliet 

Absolutely fine with that :+1: expect maybe an additional note like:

> If a file get's corrupted at one place the corrupted file get distributed to other places.

Just to make sure that not only a user mistake could cause such problems.

**Comment by RealRancor** [comment]
Closing as #568 was already merged.
