### ISSUE TITLE
Log errors after upgradde 7.0.4 -> 8.0.4

### ISSUE THREAD

**Issue by srissel** [owncloud/owncloud.org#578]
Hello,

I just upgraded from ownCloud 7.0.4 to 8.0.4, using the build in update center.
As described in several blog posts I found, I deactivated the old Calendar and Contacts app, before the actual upgrade.

The upgrade process itself went through without errors.
One thing bothers me after the upgrade:
Each time I open the App manager (.../index.php/settings/apps), two errors are reported into the log.

### Steps to reproduce
* have a running ownCloud 7.0.4 server installation
* disable Calendar app and Contacts app
* upgrade from ownCloud 7.0.4 to 8.0.4 using integrated Update Center

### Expected behaviour
No log erros after upgrade procedure

### Actual behaviour
2 log errors each time when opening App manager

### Logs
```
{
	"reqId": "0f354fc916e8571fd11afda56f649625",
	"remoteAddr": "...",
	"app": "PHP",
	"message": "Invalid argument supplied for foreach() at ...\/lib\/private\/app.php#1233",
	"level": 3,
	"time": "2015-06-17T20:42:18+00:00"
},
{
	"reqId": "0f354fc916e8571fd11afda56f649625",
	"remoteAddr": "...",
	"app": "PHP",
	"message": "preg_split() expects parameter 2 to be string, array given at ...\/lib\/private\/app.php#1230",
	"level": 3,
	"time": "2015-06-17T20:42:18+00:00"
}
```

Do you have any help on this?
Kind regards,
Sascha.

**Comment by srissel** [comment]
BTW: I tried to deactivate all installed apps, but the two errors still persist, all the same behaviour.

**Comment by jospoortvliet** [comment]
You've reported this quite well but in the wrong spot as this is where we develop the website (owncloud.org) ;-)

Could you open this as an issue on http://github.com/owncloud/core/issues ???

Thanks!

**Comment by srissel** [comment]
@jospoortvliet : thanks for the hint!

Kind regards,
Sascha.
