### ISSUE TITLE
broken links on https://owncloud.org/federation

### ISSUE THREAD

**Issue by schiesbn** [owncloud/owncloud.org#579]
Link to "user documentation" and "technical details" are broken.

I would suggest to use https://doc.owncloud.org/server/8.1/user_manual/files/federated_cloud_sharing.html for the user documentation.

not sure about the technical documentation, maybe the admin documentation? https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/federated_cloud_sharing_configuration.html

Generally I think it is a drawback that we have the ownCloud version in the URL. Would be good to have a generic URL which always points to the latest version of the documentation. Maybe the pages itself should than have a way to go back in version history. But that's more a general discussion.

cc  @jospoortvliet do you take care about the links while adding the federated cloud ids? Thanks!

**Comment by jospoortvliet** [comment]
Sorry, these links were temporary and not meant to be ready. I have linked to the 8.1 documentation, the technical one will link to a blog post from Frank about federation and the API as soon as that is out.

Yes, the static links are a problem, I will see if I can deal with that.

I also have made a youtube video showing at least half the process which I will add later (I need another video for the other half - the actual sharing, popup etc, perhaps you are able to help?)

**Comment by jospoortvliet** [comment]
closing with #609 

@schiesbn would you say I could replace the gif with the YouTube video I made? That's https://www.youtube.com/watch?v=9-JEmlH2DEg if you haven't seen it yet ;-)

**Comment by schiesbn** [comment]
@jospoortvliet yes, I think it would be nice to have the video on the page. Just make sure that we embed it in a way that it works without flash. But afaik that should be possible with youtube these days.

**Comment by jospoortvliet** [comment]
done.
