### ISSUE TITLE
Nested comments on blog not readable via mobile

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#592]
Hi,

if a blogpost like:

https://owncloud.org/blog/owncloud-8-1-coming-soon-first-release-candidate-ready-for-testing/comment-page-1

has nested comments those are nearly unreadable on a mobile phone.

**Comment by jospoortvliet** [comment]
Yeah, that's wordpress... I've decreased the nesting to only 4 items but there's not too much I can do besides that, I guess. Unless wordpress fixes this in a future release.
