### ISSUE TITLE
Make unsupported OS X and Windows more prominent on dl page

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#596]
The current download page on https://owncloud.org/install/#instructions-server is saying:

> ownCloud can be installed on Linux operating systems

As such texts are very likely not read it could make sense to explicitly state that OS X and Windows is currently not supported.

**Comment by jospoortvliet** [comment]
I added a note, but not at the top as that makes the text too long there. See https://github.com/owncloud/owncloud.org/commit/23d368a83be7ff88a468bdb1ee046d2f9156017d

**Comment by RealRancor** [comment]
I fear that people still won't read this but will see after the upcoming oC 8.1 release :-)

**Comment by jospoortvliet** [comment]
well they will notice when they try to install ownCloud Server on Windows - that won't work at all anymore... Simple.

**Comment by RealRancor** [comment]
Sure, but there are also people out there using the archives and downloading them from that page. But i think its fine and hope most people already have read about the dropped support of windows.
