### ISSUE TITLE
Change text on Tech and Me (VM)

### ISSUE THREAD

**Issue by enoch85** [owncloud/owncloud.org#599]
I would like the description text to change. 

This pre-configured VM runs on Ubuntu 14.04 with Apache and MySQL, and is <a href="https://www.en0ch.se/machine-setup/">fully configured</a> from start. Updates are managed through a built in script, and could be setup as a cron job for automatic updates. 

@jospoortvliet :)

**Comment by jospoortvliet** [comment]
I added it for now - but it really is too long. Try to shorten it by a quarter at least, please ;-)

**Comment by enoch85** [comment]
Thanks, updated now. :)

**Comment by enoch85** [comment]
ping @jospoortvliet

**Comment by enoch85** [comment]
Btw, please include the link. @jospoortvliet

**Comment by jospoortvliet** [comment]
#609 should close this ;-)
