### ISSUE TITLE
RSS feed for releases

### ISSUE THREAD

**Issue by monreal** [owncloud/owncloud.org#6]
It would be extremely helpful to have an RSS feed of owncloud.org/changelog/ as a way to be notified of new releases. The normal news RSS has too much other information and minor releases are barely mentioned. Would this be possible?

**Comment by RogerSik** [comment]
Hi tomneedham,

is there something new about the rss feeds?

**Comment by tomneedham** [comment]
So the technology is there, but I'm not sure there is always a 'post' on the website to annouce the release. @jospoortvliet You seem like the guy with answers here :) 

There has been a long request for a releases RSS feed. This is easy as we can setup wordpress to make a feed from a category of posts, something like 'releases'. But the question is if we always make such a post? And presumably the most desirable format would be a post for each version (5.0.x 6.0.x and 7.0.x etc) even when released together.

**Comment by jospoortvliet** [comment]
We currently don't really do that - there just isn't always enough to write about... I hadn't really thought about this, of course, I could do quick posts from now on to solve this. Working on one now ;-)

**Comment by untitaker** [comment]
FWIW, GitHub offers one: https://github.com/owncloud/core/releases.atom

It doesn't contain the announcement itself and is sometimes inaccurate, but it works for me so far.

**Comment by Matthias84** [comment]
@tomneedham  After 2 1/5 years we (IMHO) can close this issue, as it (surprisingly) doesn't seem to be relevant to the company / community. The webinterface notifies about updates, even if I just check it irregularly.

**Comment by LukasReschke** [comment]
> After 2 1/5 years we (IMHO) can close this issue, as it (surprisingly) doesn't seem to be relevant to the company / community.

Well. You're part of the community and Pull Requests are welcome. It's all about somebody doing it :wink:

**Comment by hurradieweltgehtunter** [comment]
After #1354 is cleared and implemented there will be a changelog/server/feed, changelog/desktop-client/feed and maybe changelog/mobile/feed.
