### ISSUE TITLE
Broken 8.1 Doc Links on https://owncloud.org/install/

### ISSUE THREAD

**Issue by flakrat** [owncloud/owncloud.org#600]
The links for the 8.1 Admin and User manuals are broken:
https://doc.owncloud.org/server/8.1.0/user_manual/
https://doc.owncloud.org/server/8.1.0/admin_manual/

These work when altered to:
https://doc.owncloud.org/server/8.1/user_manual/
https://doc.owncloud.org/server/8.1/admin_manual/

**Comment by carlaschroder** [comment]
@flakrat Where did you find the 8.1.0 links?

**Comment by flakrat** [comment]
Oops, meant to put that in the body of the ticket (was in the subject):
https://owncloud.org/install/

In section 4 under "Get more out of OwnCloud"

**Comment by carlaschroder** [comment]
Awesome, thanks @flakrat. An easy fix.

**Comment by danimo** [comment]
@carlaschroder I'm looking into it atm.

**Comment by danimo** [comment]
https://github.com/owncloud/owncloud.org/commit/aed36a8400bdcc45f4329a289614f0615db7e710

There is no world in which this could ever have worked....

**Comment by danimo** [comment]
I'll deploy this to the live system now.

**Comment by danimo** [comment]
Done.

**Comment by carlaschroder** [comment]
thanks @danimo
