### ISSUE TITLE
broken link https://doc.owncloud.org/server/8/developer_manual/bugtracker/index.html

### ISSUE THREAD

**Issue by uycarumba** [owncloud/owncloud.org#603]
Hi, the link "bugtracker" broken.

regards,

**Comment by jospoortvliet** [comment]
on what page do you find the link?

**Comment by jospoortvliet** [comment]
aah, http://owncloud.org/contribute for example. Looking at the source code, this shouldn't be broken - blegh. I'll ask @danimo and @karlitschek to look into it (see mail) as I have no idea what is wrong.

**Comment by uycarumba** [comment]
In button "Report an Issue"  -> https://owncloud.org/

**Comment by jospoortvliet** [comment]
Ok, should all be fixed now. Thanks for reporting!
