### ISSUE TITLE
Transifex Italian translation statistics

### ISSUE THREAD

**Issue by smart2128** [owncloud/owncloud.org#615]
Please, could you check why the Italian language reports wrong statistics in Transifex?
It's fully translated, but overing Italian in project languages list, it shows 0 translated, 4139 untranslated, 4053 reviewed.

Thank you in advance,
Vincenzo

**Comment by jospoortvliet** [comment]
Sorry, I'm afraid I can't help with this. Also, this is the repository for owncloud.org website development, not translations...
