### ISSUE TITLE
FAQ: Explain difference between Community/owncloud.org and ownCloud Inc./owncloud.com

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#626]
For many people the difference between the oC community at www.owncloud.org and ownCloud Inc. at www.owncloud.com are. If might be useful to have a FAQ entry for this based on the comment on https://github.com/owncloud/core/issues/13642#issuecomment-129334376

**Comment by LukasReschke** [comment]
I second this.

@jospoortvliet Would be awesome if we could have an entry that we could link to :-)

**Comment by LukasReschke** [comment]
I think we already have https://owncloud.org/faq/#communityandenterprise but it is somewhat hidden.

**Comment by RealRancor** [comment]
Ah, i see. But yes, thats really hidden as some one browsing owncloud.org is not very likely scrolling down to the last point "ownCloud for professional use"

**Comment by jospoortvliet** [comment]
well that's what I hope search and the index will help with... I can re-arrange the index of course but I'm not sure that helps too much. It is also mentioned on https://owncloud.org/history/ by the way. And owncloud.org/support explains the relationship when it comes to where to find help.

I can try and improve the faq item in this regard, but I don't know how to make it more prominent. Any suggestion is welcome, until  there is one I'll close this item as 'already done'.
