### ISSUE TITLE
FAQ: Difference between shipped apps and appstore apps like calendar

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#627]
Quite often i've read statements like "ownCloud is broken" where only non-shipped/3rdparty apps like calendar or documents where broken/not updated correctly.

It might be useful to explain the differences in an FAQ entry.

**Comment by jospoortvliet** [comment]
Any suggestions on what to say? That apps are not part of a product is rather obvious I would say, as that is the same on many other platforms people are used to (Windows, Android and so on).

**Comment by RealRancor** [comment]
The main problem here is that its not clear in general what the differences between shipped/core apps and the one installed from appstore but marked as from the "owncloud team" like:

https://apps.owncloud.com/content/show.php/Calendar?content=168707

are. Its also still in the head of people that calendar/contacts for example are core-apps.

**Comment by jospoortvliet** [comment]
We have been overhauling the app store UI, we have now 'official', 'approved' and 'experimental' with some explanation on mouse-over. This should suffice....

**Comment by jospoortvliet** [comment]
(also there's a blog coming but that is more for developers)

**Comment by RealRancor** [comment]
> This should suffice....

Unfortunately the past has shown the opposite. Especially which stuff like "hover" or similar which is just not read by many users.

**Comment by jospoortvliet** [comment]
@RealRancor 'the past' -> not sure what you refer to, this is new since ownCloud 8.1 so that's just a month... You're right in that we have QA issues for the non-shipped apps for ownCloud but those which are official should be of equal quality as those part of ownCloud - that they are not shipped is no excuse. We have to fix that, rather than tell people they are not the same quality
(and we are working on that).

**Comment by RealRancor** [comment]
>  'the past' -> not sure what you refer to, this is new since ownCloud 8.1

I refer to nothing special, just to the fact that users are lacy and doesn't read stuff like that which are hidden somewhere like an hover or an app description.

> You're right in that we have QA issues for the non-shipped apps for ownCloud but those which are official should be of equal quality as those part of ownCloud - that they are not shipped is no excuse. We have to fix that, rather than tell people they are not the same quality
(and we are working on that).

Ok, that sounds good. So let us close this if the problems with the QA of the non-shipped but "official" apps are solved in the future.
