### ISSUE TITLE
Changelog shows wrong version no. for v8.0.6

### ISSUE THREAD

**Issue by rakekniven** [owncloud/owncloud.org#639]
See https://owncloud.org/changelog/
It says 8.0.5 but it should be 8.0.6 released on 11th august.

**Comment by karlitschek** [comment]
@jospoortvliet Can you help here?

**Comment by jospoortvliet** [comment]
fixed in https://github.com/owncloud/owncloud.org/commit/d7cf8bbe91fa7309718f0ed45e4b7bfbca41f9b2
