### ISSUE TITLE
News page has many user links which gives a 404

### ISSUE THREAD

**Issue by rakekniven** [owncloud/owncloud.org#640]
On https://owncloud.org/news/ there you have user avatars and links next to them e.g. Evert Pot.
Link target is https://owncloud.org/user/?user=evert which gives me a "Sorry, but the page you were trying to view does not exist."

There are many of it.

**Comment by jospoortvliet** [comment]
Hmm, it is not the only one which is broken - they all are (see owncloud.org/contact).

And really, I have no clue what broke it or how to fix it :( This is stuff once set up by (probably) @tomneedham

**Comment by tomneedham** [comment]
Fixed. The links should go to https://github.com/owncloud/owncloud.org/blob/master/page-user.php, but the page was missing in Wordpress.

**Comment by jospoortvliet** [comment]
@tomneedham thanks a lot (and glad to see you around again, I hope I managed to keep the house in order while you were away)
