### ISSUE TITLE
Link by transifex to owncloud.org gives 404

### ISSUE THREAD

**Issue by rakekniven** [owncloud/owncloud.org#651]
![bildschirmfoto 2015-08-20 um 21 34 50](https://cloud.githubusercontent.com/assets/2069590/9393666/86d8ea0e-4783-11e5-9c5f-52d472d0a1a7.png)
Just logged in at transifex and selected ownCloud project. Link "help pages" shows "not found" on owncloud.org

**Comment by jospoortvliet** [comment]
what page does it link to? I don't have the power to change it on transifex, though, but it probably means to link to our documentation about translating - not sure if we have it and if so, where...

**Comment by rakekniven** [comment]
Sorry Jos, the target is https://owncloud.org/contribute/translation/

**Comment by jospoortvliet** [comment]
Then let me find @tomneedham here to teach me how to create redirects...

**Comment by jospoortvliet** [comment]
Ok. I decided to create a simple page. Any suggestions for what else to put there? Let me know.

https://owncloud.org/contribute/translation/

**Comment by rakekniven** [comment]
Maybe write one sentence about how to report translation issues.
Personally I do not know?
* Write to translation mailinglist?
* Report to specific repo at github?
* Another way?

**Comment by jospoortvliet** [comment]
will look at that. I honestly don't know any better...
