### ISSUE TITLE
Wrong link to stable release https://owncloud.org/install/

### ISSUE THREAD

**Issue by 1inux-de** [owncloud/owncloud.org#670]
https://owncloud.org/install/ points to old 8.1.1 and not to the latest 8.1.2.

**Comment by jospoortvliet** [comment]
there is no 8.1.2 yet, that shouldn't be in the changelog either. We're still fixing something and finishing testing ;-)

**Comment by enoch85** [comment]
@jospoortvliet Will 8.1.2 ever be released?

**Comment by jospoortvliet** [comment]
@enoch85 we'll skip it and release 8.1.3, hopefully today. Coming with a blog about the community VM and an explanation for the delay ;-)
