### ISSUE TITLE
Redirect lists.owncloud.org to mailman.owncloud.org

### ISSUE THREAD

**Issue by strugee** [owncloud/owncloud.org#673]
Currently lists.owncloud.org does a redirect to the homepage, but as lists.* is a widely-used subdomain for mailing lists (and so people may just try it and see if it works), it should redirect to mailman.owncloud.org instead.

**Comment by jospoortvliet** [comment]
@danimo needs server access... I can shoot in a sysadmin ticket if you like?

**Comment by danimo** [comment]
@jospoortvliet No need. Done.

**Comment by jospoortvliet** [comment]
thanks!
