### ISSUE TITLE
our promote page needs some design love...

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/owncloud.org#674]
the page on owncloud.org/promote - which is about joining the conversation around ownCloud - is messy. But I don't really know how to clean it up... cc @owncloud/designers to the rescue? @jancborchardt @MorrisJobke 
![join the conversation - owncloud org](https://cloud.githubusercontent.com/assets/551757/9782727/b523d6c2-579f-11e5-98da-3d7f52148e28.png)

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by Kawohl** [comment]
@felixheidecke could you  please hep out here then?

**Comment by hurradieweltgehtunter** [comment]
outdated after relaunch. But I am open to every (design) improvment. Please open new issue.
