### ISSUE TITLE
Static Download Link

### ISSUE THREAD

**Issue by ahousseini** [owncloud/owncloud.org#688]
Our company manages thousands of OS X computer with a MDM solution. To keep applications up-to-date we use shell scripts which grabs the version number from the developer website and compare the version with the installed application. If there is an newer release available it downloads the package and installs it automatically. To create those scripts its easier when there is page with the current version and a static download link for the installer. Would it be possible to create those for the ownCloud sync client app?

For example:
- https://owncloud.org/getcurrentversionmacdesktop.php with output 2.0.1
- https://download.owncloud.com/desktop/stable/ownCloud.pkg

Here an example for another application:
- https://www.lehreroffice.ch/services/update/getcurrentversion.php
- https://www.lehreroffice.ch/lo/dateien/easy/lo_osx.zip

Would be really nice!

**Comment by jospoortvliet** [comment]
We can probably set up a link or something. @danimo is that possible?

**Comment by danimo** [comment]
> If there is an newer release available it downloads the package and installs it automatically.

How does it know?

**Comment by oureas** [comment]
It would compare the bundle version of the installed application with the website.

**Comment by danimo** [comment]
@oureas So it would constantly poll the URL and keep re-downloading the bundle? or does it issue HEAD requests and use that?

**Comment by oureas** [comment]
Yes it checks the URL daily and if necessary it downloads the package.

**Comment by oureas** [comment]
Any new informations about this?

**Comment by ahousseini** [comment]
Sorry to bother you guys. Any idea how to implement this?

**Comment by jospoortvliet** [comment]
sorry, there's nothing I can do and daniel is just back from holiday. This probably isn't super high on his list of priorities...

**Comment by RealRancor** [comment]
@ahousseini 

Little bit hidden but the client is using the following updating URL which seems to provide all needed infos:

https://updates.owncloud.com/client/index.php?version=2.0.1&platform=win32&oem=ownCloud

Thats for win32 but maybe also exists for OS X and Linux.
