### ISSUE TITLE
Dead link on encryption how-to-page

### ISSUE THREAD

**Issue by tflidd** [owncloud/owncloud.org#714]
https://owncloud.org/blog/how-owncloud-uses-encryption-to-protect-your-data/

There is a dead link referring to owncloud installation manual (second link after heading "How does ownCloud use encryption?") for transport encryption. New link could be:
https://doc.owncloud.org/server/8.1/admin_manual/installation/source_installation.html#enabling-ssl

**Comment by jospoortvliet** [comment]
Thanks, fixed!
