### ISSUE TITLE
What to say about client periodic full scan?

### ISSUE THREAD

**Issue by phil-davis** [owncloud/owncloud.org#719]
The FAQ text currently says:
For example, the file-change-notifications on Linux and Windows are not 100% reliable in all cases, so just-to-be-sure we run a full file system scan every few minutes. Yes, that eats battery life, but it does ensure you do not lose any of your files!

I think that the full scan nowadays is only ever 2 hours. And the exact implementation will keep changing.

What should be said here in the FAQ that will be more durable over time?

For example, I made just a small change in this PR https://github.com/owncloud/owncloud.org/pull/718

**Comment by jospoortvliet** [comment]
I think that 'periodically' is a very good way of putting it, thanks.
