### ISSUE TITLE
Wrong GPG-Key on https://owncloud.org/install/#instructions-server

### ISSUE THREAD

**Issue by jnweiger** [owncloud/owncloud.org#724]
https://owncloud.org/install/#instructions-server

There are 4 tabs: Archive Files, Web Installer, Packages, Appliances.
All 4 tabs advertise https://owncloud.org/owncloud.asc as *the* public ownCloud key.

I don't think that the key is used (or usable) with Packages. I am pretty sure, the key is not used with the community appliance.

Find a copy of the public key used for packages on OBS.

Please copy this on owncloud.org and link it from the Packages tab, using its key ID 1024D/BA684223 as link text. (We don't have just *the* key. We have multiple, I am afraid.)

<pre>
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.5 (GNU/Linux)

mQGiBE8ySNwRBACKcsg4AceGW7vuOSywcGiiNZg4I8vIzn7zphgj+s6/i2/hs8TQ
TOHy1s3b0f32ani3sBRmTWtgNv8+HSaKSVUcNqqNL+Jy6Pulyao7amGTtvqVKmuz
6ADrbVz0SxWmzTlSctdxK3g3yRSb+vfYrBPrbXNCNB5g9C/uK1uh0fpj1wCgn3MX
GFlZsO3bF7SNqqYlzpV6DM0D/AjnBlxTwRJOA1sLAVSXipLOdkjo00OQ8jgOFDio
oJsqLtsscNGocPCqNRo6QSVQKNs5sfYP2GXWTnPVM5oJI1p6bjuADRE8mneJrJvF
Uc+Mt1MdS6ttF4tVqd5Ncc8LKYQJRn+AtiuxAAayAA35JOslnMM0bqSYMlw4BJTP
8TlPA/4r+k+ucz3cJtM2aaL/ngUdrhmGKfGK7npXA3Ic6FzQo2NlJyKfWjSsR8x+
oN7tKEpuYxE5fcdbWd3v+4Ypx0LYMgBT1pUgI09AXxrx1cLRZI4yovrvQJgiA4Mh
CZ0eFkJJ1nwQR3NPMj5soar+7d3Ubc2EqkESGm0CgGtjgg+7HrQ6aXN2Om93bkNs
b3VkIE9CUyBQcm9qZWN0IDxpc3Y6b3duQ2xvdWRAYnVpbGQub3BlbnN1c2Uub3Jn
PohmBBMRAgAmBQJU2MJUAhsDBQkJxSl4BgsJCAcDAgQVAggDBBYCAwECHgECF4AA
CgkQl3xDqLpoQiMpOQCggCpaq5yz8C3ckqEr0RkTjICcQYMAnRvjarxoY6iSThDN
7vgxE1Fe8X5EiEYEExECAAYFAk8ySNwACgkQOzARt2udZSPlpwCfQZKNN8Rxx0LE
BF32EYXBdEvkMYYAoIt3lfXL8uwmjvyljzb0JgBQN1cF
=FJ6Q
-----END PGP PUBLIC KEY BLOCK-----

</pre>

**Comment by jnweiger** [comment]
@jospoortvliet can you help with this, please!

**Comment by jospoortvliet** [comment]
Seems that that key is already there: 
https://github.com/owncloud/owncloud.org/blob/master/assets/files/obs-release-signing.gpg

And it is already linked to in the packages section, read on the left of the page:
![bla](https://cloud.githubusercontent.com/assets/551757/10164618/d07516d2-66ba-11e5-9a85-2d03aa366b98.png)

So that seems all good, right?

**Comment by jnweiger** [comment]
Cool. Thanks!

On the right hand side under Security note: There is 'Find the public ownCloud GPG key here.' This is what I saw first, when looking for something GPG related. Mabye we should remove that one then?

**Comment by jospoortvliet** [comment]
well, dunno, it's only the GPG key for the tarballs, I suppose? Then it does indeed make little sense on the packaging tab...

**Comment by jospoortvliet** [comment]
I'm keeping the key there, it should imho be mentioned.
