### ISSUE TITLE
app review page malfunction

### ISSUE THREAD

**Issue by pbek** [owncloud/owncloud.org#736]
Hello my dear friends at ownCloud,

it seems that the app review page at
https://owncloud.org/contribute/appform/
is not working as it should. If you submit a app only a blank page (plus menu) is shown.

I also tried to subscribe to the app review mailing list last week but got no answer so far. :(
 
Cheers, Patrizio
 
PS: I wanted to submit https://apps.owncloud.com/content/show.php?content=170674

**Comment by LukasReschke** [comment]
@jospoortvliet FYI

**Comment by pbek** [comment]
Is there a way to submit apps in the meantime, @cmonteroluque ?

**Comment by cmonteroluque** [comment]
Hoping to have this fixed early this coming week

**Comment by pbek** [comment]
Sounds great! Many thanks!

**Comment by jospoortvliet** [comment]
I'm on it now. The code hasn't changed in 2 months but somehow stopped working. I am baffled and trying to figure out what's wrong...

**Comment by pbek** [comment]
That's a classic! :)
Maybe something around Wordpress got auto-updated or there were some PHP changes on the server...

**Comment by jospoortvliet** [comment]
thing is, it also doesn't work in my local setup, and that has certainly not changed its wordpress. And as server it just runs on ```php -s  localhost:5000``` so there's not much "server" there ;-)

I really dunno what is going on...

**Comment by jospoortvliet** [comment]
ok this'll have to wait until later this week, as I have to focus on the release tomorrow. Somehow, the PHP doesn't run - can't figure out what is wrong.

**Comment by pbek** [comment]
*giggle* `php -s localhost:5000`
wordpress is also able to auto-update itself "magically". :)

good luck on the release and the repair!

**Comment by jospoortvliet** [comment]
https://mailman.owncloud.org/pipermail/appsreview/2015-October/006067.html proves that the form works right now. @pbek that is on staging, going to deploy RIGHT NOW. Tell me if it works for you, then close this!

**Comment by pbek** [comment]
The page works now! Thanks a lot, @jospoortvliet !
I hope I'll get an answer too, because I already subscribed to the mailing list (and posted my request) some weeks ago. :)
