### ISSUE TITLE
Where is the OC 8.2RC1 tarball ?

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud.org#738]
I wasn't able to find them within 1-2 minutes, this is bad UX.

Steps:

1. Go to owncloud.org
1. Click blue Download on the top right
1. Click "Download" under "Download ownCloud": popup appears
1. Looking at the top, it's 8.1.3, scan the page, look for anything about development version or beta version => nope
1. Try "older versions or major releases?" => top of page shows 8.1.3, probably not here either
1. Let's try "Release channels" then (Release channel sounds more like something for official major releases, not beta)
1. Scroll down: ok so there's a row with "Beta" but it only has "Linux packages", let's click that => nope. Go back.
1. At this point I give up

Where is it ?

**Comment by PVince81** [comment]
If we want people to help testing RCs then it would be good to also have the tarballs easy to find @karlitschek @jospoortvliet @jancborchardt

**Comment by PVince81** [comment]
Okay, maybe forgot to publish the archive file so the "Archive" button is missing on the "Beta" row.

Still, it took me a while to reach that page. Would be good to make it more visible in the first popup.

**Comment by jospoortvliet** [comment]
It's right there: 
![bla](https://cloud.githubusercontent.com/assets/551757/10578866/1b12e998-7675-11e5-9fcd-ab75039d2106.png)

**Comment by PVince81** [comment]
Thanks, I totally overlooked that part, maybe because it's at the very end and not together with the other "Download" button.

Maybe the button should say "Download beta package", something that catches the eye.
Because I don't want to read all the text up to the end to find out it says "grab a daily build or beta package".

Also "Testing packages" somehow sounds like "daily build" which I didn't want, but sounds less like "RC" packages. But maybe that's just me.

**Comment by jospoortvliet** [comment]
@PVince81 you DID find the right thing, then, as the Testing packagers only have daily builds. If you want Beta/RC, you did find the right place: Release Channels. I don't HAVE links to beta packages anywhere on the site, if people want that they have to subscribe to the mailing list.

We could add them, of course, to the release channels Beta section, but they require website updates on every beta/RC update unless we find/create a stable URL for that.

@cmonteroluque that is something you probably will have to help with - is there a fixed place where people can download beta's and RC's right now on download.owncloud.org? If so, I can link to that. If not - we could create it.

**Comment by PVince81** [comment]
Hmmm ok. The context is usually when people ask me in github issues where to find the RC packages after I told them to retry with the beta/RC version. That's when I go link hunting.
As you said I could just have a look at the mailing lists, but I'm not sure whether most bug reporters are on such mailing lists.

Also regarding beta vs dailies, some people might be more willing to put betas/RCs on their servers than dailies. I personally don't mind putting a RC on my productive server as RC should be stable enough already, but wouldn't want to have a daily build there.

**Comment by jospoortvliet** [comment]
see #745 - it should address most of your concerns with exception for the beta/RC tarballs, I have no link for that.

**Comment by cmonteroluque** [comment]
https://github.com/owncloud/owncloud.org/issues/738#issuecomment-149476802 Agreed. I added to a working "release checklist"
