### ISSUE TITLE
Redis file locking and streaming problem

### ISSUE THREAD

**Issue by briskspirit** [owncloud/owncloud.org#748]
### Steps to reproduce
1.Install Redis from apt-get
2. Enable file locking by Redis in config.php

### Expected behaviour
1. Video streams must work fine as without file locking.

### Actual behaviour
1.Now streaming(all video player apps from store and native one) will be broken, "wrong sorce".
2.When downloading files through browser it writes in progress "10Mb from ?", so no info about file size.

### Server configuration
Debian 8.2

**Web server:**
Apache/2.4.10

**Database:**
MySQL

**PHP version:**
PHP 5.6.13-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
8.1.3 

**Updated from an older ownCloud or fresh install:**
Fresh install

Text explanation:
Installed Redis for caching (first was on APCu) and file locking. 
All seems to work fine, but streaming apps like Video Viewer and Video SJ don't work + when downloading files through browser it writes in progress "10Mb from ?", so no info about file size.
Without file lock all is fine(with caches enabled)
Browser - Safari. xsendfile installed.

Is this mime/headers problem? 
https://forum.owncloud.org/viewtopic.php?f=31&t=31007&p=99105#p99105

**Comment by LukasReschke** [comment]
Please file in core using the issue template - THX.

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by briskspirit** [comment]
Got where from problem comes... Redis + g-zip conflict. Works fine just one of them. Troubles with headers as I think.

**Comment by briskspirit** [comment]
Seems that I have found problem, @LukasReschke close please or even delete this issue.

**Comment by RealRancor** [comment]
@briskspirit You can close this issue on your own by hitting the "Close" button under the comment field.
