### ISSUE TITLE
Forgot to include CA bundle in OC 8.2 ?

### ISSUE THREAD

**Issue by briskspirit** [owncloud/owncloud.org#754]
Hi.

Got a problem after upgrade from 8.1 : No internet connection. And error:
Could not get application: SSL CA bundle not found: /var/www/owncloud/resources/config/ca-bundle.crt

downloaded CA from 8.1 and put into resources/config(created) - works fine. 
debian 8 repo with OC 8.2

**Comment by briskspirit** [comment]
Other errors:

file_get_contents(/var/www/owncloud/resources/config//mimetypealiases.dist.json): failed to open stream: No such file or directory at /var/www/owncloud/lib/private/files/type/detection.php#115

array_merge(): Argument #2 is not an array at /var/www/owncloud/lib/private/files/type/detection.php#99

Invalid argument supplied for foreach() at /var/www/owncloud/lib/private/files/type/detection.php#102

This all after fixing CA bundle problem. In App there is only Enabled and Disabled, no appstore apps at all. Seems like bad debian package?...

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by RealRancor** [comment]
@LukasReschke Right place to discuss this?

**Comment by LukasReschke** [comment]
No. But needs to get fixed anyways soon. So let's save time instead of moving it around :smile:

**Comment by jnweiger** [comment]
8.2.0 has
-rw-r--r-- nobody/nogroup 225828 2015-10-19 15:21 owncloud/apps/files_external/3rdparty/Dropbox/OAuth/ca-bundle.pem
-rw-r--r-- nobody/nogroup  258423 2015-10-19 15:21 owncloud/resources/config/ca-bundle.crt

8.1.3 has
-rw-r--r-- nobody/nogroup 258423 2015-09-10 17:34 owncloud/config/ca-bundle.crt
-rw-r--r-- nobody/nogroup 225828 2015-09-10 17:34 owncloud/apps/files_external/3rdparty/Dropbox/OAuth/ca-bundle.pem

Apparently a /resources/ folder was introduced.
@DeepDiver1975  Should I move things around during packaging to fix this???

**Comment by karlitschek** [comment]
no moving around in packaging please. owncloud 8.2 should find it at the new location

**Comment by briskspirit** [comment]
There is no resources folder and OC can't find it at new place, same with mime types location.
If I don't put CA in resources folder - it will write errors and that OC isn't connected to internet...

**Comment by jnweiger** [comment]
Ah, that is the error. Thanks @briskspirit for your report!
resource folder is silently skipped when building debian packages. Rebuilding.

**Comment by briskspirit** [comment]
Thanks for your fast reply! ;) Mime types error will be fixed too?
Will try to reinstall after you build new packs

**Comment by karlitschek** [comment]
Argggghh. @jnweiger How can we avoid this in the future? This happens several times now. When something is in the release tar/zip than this means usually that it also has to be in the rpm, deps.
We have to change the way we work here so that in the future we don't forget new files and folder anymore.
@cmonteroluque @dragotin

**Comment by briskspirit** [comment]
@jnweiger write please when deb8 package will be ready

**Comment by jnweiger** [comment]
@karlitschek This issue is there since beta1. Remained unnoticed. Call QA.
I'll have to rebuild all VM images now. Gaaah.

**Comment by LukasReschke** [comment]
@karlitschek Our 9.0 code integrity scanner would catch these situation. Well, not that it helps now but at least in the future. ownCloud would refuse to install then.

**Comment by jnweiger** [comment]
I had my own integrity scanner in the packaging code, but had to disable it because of too many false positives. :-(

**Comment by jnweiger** [comment]
@briskspirit Please check out owncloud_8.2.0-2.1_all.deb   from the debian 8 repo. Make sure you see the '-2.1' buildrelease number  in there. Not '-1.1'

**Comment by jnweiger** [comment]
I can now see the resources folder in the DEB package. Fixed. Closed.

**Comment by briskspirit** [comment]
Yes, resources is on place and there is no errors about CA and etc.

But still few problems:
1. Updater app in Administrator menu writes {{newVersion}}
2. Video Viewer(native app) and VideoJS Sublime don't open on supported files, starts to download.
3. Mail app(Error to load account settings(from DB?)), Music app, Log reader app - broken.
4. Calendar+ app layout (theme) broken.
===All this have worked in 8.1.3

I am very sorry, but are you sure that 8.2 is stable?...

**Comment by RealRancor** [comment]
@briskspirit Three of the four noted issues are issues within non-core apps and should be reported to the issue tracker of those apps. This has very likely nothing to do with the stability of 8.2...
