### ISSUE TITLE
Gallery broken for hosted demo?

### ISSUE THREAD

**Issue by maikhoepfel** [owncloud/owncloud.org#755]
Hi all,

I just had a look through the demo and wanted to look at the new gallery. Upon going to https://demo.owncloud.org/index.php/apps/gallery/#Photos, I only saw placeholder images and clicking them caused my browser to download them. No gallery functionality as far as I could tell. 

![image](https://cloud.githubusercontent.com/assets/509427/10612362/b5c3df0c-7750-11e5-8fa4-b593b003afd5.png)

Maybe I'm misunderstanding something. Just wanted to report in case I'm not.

Cheers,

Maik

**Comment by LukasReschke** [comment]
We're working on this.

**Comment by LukasReschke** [comment]
cc @stp-ip

**Comment by maikhoepfel** [comment]
:+1: Cool, thanks for the crazy fast response. Do with the ticket what you wish.

**Comment by jospoortvliet** [comment]
(this is the owncloud.org bugtracker, a problem for gallery belongs in https://github.com/owncloud/gallery/issues )
