### ISSUE TITLE
New Config Parameter for HTTP Header HSTS and HPKP

### ISSUE THREAD

**Issue by Georg-Git** [owncloud/owncloud.org#762]
HTTP Headers for Strict Transport Security (HSTS) and Public Key Pinning (HPKP) is easy to enable via header set in .htaccess file.

But this http headers are not send with php running in cgi mode.

So I added in
/lib/private/response.php:
```
    header('Public-Key-Pins: " ..YourPINData.."; max-age=604800;"');
    header('Strict-Transport-Security:max-age=15768000; includeSubDomains');
```
Of course this is a dirty solution.

So I request a new config parameter to set individuel http headers for the domain.

**Comment by RealRancor** [comment]
Hi,

@Georg-Git 
please re-open in: https://github.com/owncloud/core/issues if you think this should be included in the oC code. The issue tracker here is for issues within the https://www.owncloud.org page.
