### ISSUE TITLE
https://owncloud.org/features/ lists "New in ownCloud Server 8.1"

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#763]
https://owncloud.org/features/
-> New in ownCloud Server 8.1 probably should be "New in ownCloud Server 8.2"

The button "Details on ownCloud Server 8.2" on the right side is also linking to:

https://owncloud.org/eight-one/

instead of:

https://owncloud.org/eight-two/

**Comment by RealRancor** [comment]
Not directly related but:

https://owncloud.org/blog/upgrading-to-owncloud-server-8-2/  -> Troubleshooting

links to an upgrading thread at the forums for oC 8.1. There is currently none for oC 8.2 available.

**Comment by jospoortvliet** [comment]
About the forums, it seems the upgrading threads for 8.0, 8.1 and on are the same - so that's a keeper, unless you guys decide for another thread.

About the features page - good catch, created a fix.

**Comment by RealRancor** [comment]
> About the forums, it seems the upgrading threads for 8.0, 8.1 and on are the same - so that's a keeper, unless you guys decide for another thread.

Nope, in this case not. :-)

8.0.x had another thread: https://forum.owncloud.org/viewtopic.php?f=31&t=26310

as 8.1.x: https://forum.owncloud.org/viewtopic.php?f=31&t=29102

For 8.2.x none exists as there are currently no urgent issues during the upgrade which needs to be documented from my PoV.

**Comment by jospoortvliet** [comment]
Ah ok, my mis-understanding then. Well, good with me - but if there IS a topic at some point, tell me and I link to it.

Fix for features page is live.

**Comment by nickvergessen** [comment]
The only thing I know so far is users updating their board incorrectly:

> https://github.com/owncloud/activity/issues/419#issuecomment-149830559
> ---
> You didn't delete the old files and just uploaded the new files into the existing folder.
>
> https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

I posted this 7times atm or something. But other then that I don't know any problem either

**Comment by RealRancor** [comment]
@nickvergessen 
Yes, thats an issues which happens since ages :-/

**Comment by jospoortvliet** [comment]
Well, 9.0 will have some integrity checking which should help with that, right? ;-)

**Comment by MorrisJobke** [comment]
> Well, 9.0 will have some integrity checking which should help with that, right? ;-)

Correct ;)

**Comment by jospoortvliet** [comment]
:clap:

**Comment by RealRancor** [comment]
@jospoortvliet There is now a known issues / upgrading thread at the forums available:

https://forum.owncloud.org/viewtopic.php?f=36&t=31252

**Comment by jospoortvliet** [comment]
@RealRancor updated the blog post ;-)
