### ISSUE TITLE
ca-bundle problem with openBSD 5.8

### ISSUE THREAD

**Issue by stephengraf** [owncloud/owncloud.org#765]
Re: cURL error 60: SSL certificate problem: unable to get local issuer certificate

I started testing openBSD 5.8 which shipped with ownCloud 8.1.0. When trying to add the store apps I was getting the cURL error 60. After reading the last posts to the GitHub track, https://github.com/owncloud/core/issues/17446, two posters fixed their problems by replacing the ca-bundle that comes with ownCloud with a bundle from some other source. I replaced the ownCloud bundle with one that shipped with the openBSD 5.8 distribution and the problem went away.

Although the ca bundles on some distributions might be outdated, I suspect that the bundles with those systems would have worked and not created all the problems that introducing another bundle into owncloud did. In my test I was using openBSD 5.8 which was just released and it came with owncloud 8.1, php 5.6, libressl 2.0 and I doubt any of this is out of date. I had no problem using cURL from a command line to get to the app store, which would have used the openBSD supplied bundle. Owncloud 8.1.3 did not complain about a "buggy" ssl vervsion, yet I could not get to the app store from owncloud admin. I tried changing the ca bundle because someone running SUSE 12 was able to resolve the same problem in that way.

The issue is, should owncloud be forcing ca bundles when it seems to be causing problems. Do I even want owncloud to be my source of security certificates? It seems that owncloud just copied the bundle from some other source. How much effort went into verifying the security of the bundle? I use openBSD partly because of its emphasis on security and would much rather depend on openBSD for things like openssl and ca bundles.

I would like to recommend that owncloud make the choice of ca bundle an option in config.php with documentation to indicate that the default supplied with owncloud might not work on all systems.

**Comment by karlitschek** [comment]
Sorry. This is the bugtracker for the owncloud website. closing as unrelated. This seems to be a packaging problem. Please use the official release for ownCloud which should work just fine
