### ISSUE TITLE
Wrong link for installation manual on download page?

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#772]
Hi,

https://owncloud.org/install/#instructions-server

currently contains:

``Follow the ownCloud Admin Manuals’ installation chapter.``

which links to https://doc.owncloud.org/server/8.2/admin_manual/#installation. Seems that should be linked to https://doc.owncloud.org/server/8.2/admin_manual/installation/index.html or am i wrong?

**Comment by jospoortvliet** [comment]
Sir, yes, sir. Fixing!

**Comment by jospoortvliet** [comment]
Fixed in https://github.com/owncloud/owncloud.org/commit/8db5f24ba11eefd043ceb58341be269ddbabebce
