### ISSUE TITLE
Download page has too many colors

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/owncloud.org#780]
https://owncloud.org/install/#instructions-server

* [x] the close x in the top right should just be dark, not orange
* [x] the link color should be #35537a, just like in the new frontpage PR at https://github.com/owncloud/owncloud.org/pull/776, same for the primary action buttons such as download (@jospoortvliet)
* [x] the background of the »Latest stable version« bubble should also be that same #35537a color.
* [x] there’s a thin white line below the header where the overlay isn’t high enough.

**Comment by jospoortvliet** [comment]
![4](https://cloud.githubusercontent.com/assets/551757/11121669/710f963a-8957-11e5-8a4e-595272d8636a.png)

I do not understand what you mean with link color. The base action buttons all over the ownCloud website will become the new style once the frontpage PR is merged. I've implemented these changes as part of that PR, btw.

**Comment by jancborchardt** [comment]
With link color, I mean the color of every single link. That is the light blue of the tabs, of the text like »changelog«, ».tar.bz2«, ownCloud Admin manual«, »Release Channels« etc. The color that links are styled with. :)

**Comment by jancborchardt** [comment]
And of course, the background of the download button in the top right.

**Comment by jospoortvliet** [comment]
@jancborchardt ok, link color, I can change that, no problem. Do you want to change this for the entire owncloud.org website or just on the download page or even just in this popup?

**Comment by jospoortvliet** [comment]
![install - owncloud website](https://cloud.githubusercontent.com/assets/551757/11151235/262a338e-8a2c-11e5-9278-9c5706100cd4.png)
![install - owncloud website 1](https://cloud.githubusercontent.com/assets/551757/11151236/2906112c-8a2c-11e5-8db8-a7cae64105c4.png)
![owncloud website 3](https://cloud.githubusercontent.com/assets/551757/11151237/2b5117c4-8a2c-11e5-95a4-c01b9e5a216a.png)
@jancborchardt see above. I can make the links #35537a (I did it for both visited and unvisited) but I'm not sure if it is a great step forward... Note our text is #1D2D44 which is just too close at least on my screen I can barely see the links anymore.

Making the buttons #35537a (and text white) gets you this:
![features - owncloud website](https://cloud.githubusercontent.com/assets/551757/11151603/50664a46-8a2e-11e5-9be7-8ff32b42020e.png)

Now THAT makes for one hell of a boring site. Nothing stands out. I don't think this looks good at all... why don't we just make it all black and white then ;-)

**Comment by jancborchardt** [comment]
Why is the text in our brand color? :D it should be black of course.

**Comment by jancborchardt** [comment]
And if that's still too little contrast, try #55739a as link color :)

**Comment by jospoortvliet** [comment]
This is what it would look like. Sorry, but I find it terrible... The lighter blue of the buttons was so much better. Also, the black text on white background is so much more harsh than the dark blue on grey we had before - just compare... Are you sure you want to go this way?
![comparision](https://cloud.githubusercontent.com/assets/551757/11153702/ede5e356-8a3a-11e5-8ba9-6756d6faf928.png)

**Comment by jospoortvliet** [comment]
How about keeping the link color as-is but making those buttons #55739a:
![dev conversations 3](https://cloud.githubusercontent.com/assets/551757/11163263/857ea030-8ac8-11e5-9a33-3cd0b2eb8ec7.png)
![dev conversations 3](https://cloud.githubusercontent.com/assets/551757/11163270/9a6735b6-8ac8-11e5-904f-0163290c8923.png)

If you make them the same blue as the background it just looks so bland... And links you can't make to dark as then you simply don't see them. Not everybody has a great quality, well calibrated screen ;-)

**Comment by jancborchardt** [comment]
The black text and #55739a looks way better than the current soup of blue. It should definitely be white background and black text, just like in ownCloud itself.

We could try and combine that with your suggestion of making the buttons #55739a (incl top right Download button please) and keeping the current brighter blue for link colors?

**Comment by jospoortvliet** [comment]
@jancborchardt then we should also change the style of headers and the font itself to match that of ownCloud... To be more like this:
![6](https://cloud.githubusercontent.com/assets/551757/11181203/b898c98e-8c60-11e5-822b-6b5fb136a8ed.png)

Can you tell me or point me to some details about that, eg sizes, weight, etc?

**Comment by jancborchardt** [comment]
@jospoortvliet yup, totally agree! Right-click inspect is your friend ;)

**Comment by jancborchardt** [comment]
Just kidding, here are the sizes. All headers in Light weight (font files in the [core repo](https://github.com/owncloud/core/tree/master/core/fonts)). We only use Light and Semibold, the Regular is just as fallback for older systems. We could try to not use Regular on the website too if it works.

The sizes relate to the default font size of the ownCloud web interface. Might need some proportional tweaking up since I think the base font size of the website is slightly larger.

And there is no h4 or below – when you reach that you know the nesting is too complex, so avoid it.

```
h1, h2, h3 {
	font-weight: 300;
}
h1 {
	font-size: 40px;
}
h2 {
	font-size: 20px;
	margin-bottom: 12px;
}
h3 {
	font-size: 15px;
	margin: 12px 0;
}
```

**Comment by jospoortvliet** [comment]
You are a liar, @jancborchardt  - ownCloud uses ```#555``` rather than black!

Here's what it looks like on .org for the features page with either black or ```#555```:
![features - owncloud](https://cloud.githubusercontent.com/assets/551757/11253184/553ee860-8e3a-11e5-90d3-89c770590a44.png)
![features - owncloud 1](https://cloud.githubusercontent.com/assets/551757/11253187/575037a8-8e3a-11e5-9f32-3ab83ca865d7.png)

I am feeling a LOT better about this. Not perfect, though, tell me what to improve while we wait for that background picture from mr Karlitschek!

**Comment by jospoortvliet** [comment]
@jancborchardt but I am sure you have some detailed comments... ;-)

**Comment by jospoortvliet** [comment]
I'm going to close this as I think I addressed everything. We can further fine tune more fonts and stuff later.
