### ISSUE TITLE
FAQ has broken indentation

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/owncloud.org#803]
Seems like a missing `</li>` or so…

https://owncloud.org/faq/#upgradeyet
![2015-12-03_23-39-28](https://cloud.githubusercontent.com/assets/878997/11576468/1e66b82a-9a17-11e5-9094-e93171f744bc.png)

**Comment by LukasReschke** [comment]
@jospoortvliet

**Comment by jospoortvliet** [comment]
fixed in https://github.com/owncloud/owncloud.org/commit/720681512efea0c2ca2e385e91f77f3f7deac39d
