### ISSUE TITLE
Clicking documentation in the navigation shifts the whole navigation over

### ISSUE THREAD

**Issue by andreasn** [owncloud/owncloud.org#804]
Regular page:
![screenshot from 2015-12-04 12-23-09](https://cloud.githubusercontent.com/assets/209895/11588575/dae64582-9a81-11e5-8398-79b1b34c0866.png)

Support page:
![screenshot from 2015-12-04 12-23-20](https://cloud.githubusercontent.com/assets/209895/11588582/f48da516-9a81-11e5-82f2-f314284451ba.png)

It seems the Support page also misses the link to "Enterprise Edition"

**Comment by danimo** [comment]
The docs have not yet been adoped to the new style. Please open an issue in https://github.com/owncloud/documentation/issues/

**Comment by jospoortvliet** [comment]
I'll take care of it, let's just track it here.

**Comment by jospoortvliet** [comment]
fixed.. By danimo and the last little pieces here https://github.com/owncloud/documentation/pull/1941

**Comment by andreasn** [comment]
Thanks for the quick turnaround on this!
