### ISSUE TITLE
Scrolling horizontally on doc.owncloud.org

### ISSUE THREAD

**Issue by Henni** [owncloud/owncloud.org#807]
http://doc.owncloud.org scrolls horizontally.

This could be prevented by removing the `.row` class from the social icons, but this may break other stuff.

![image](https://cloud.githubusercontent.com/assets/1267827/11655160/b4ddd652-9dab-11e5-8ddb-0a2e451e975e.png)

**Comment by jospoortvliet** [comment]
lemme fix that. Thanks for reporting!

**Comment by jospoortvliet** [comment]
should be fixed in https://github.com/owncloud/documentation/pull/1941

**Comment by Henni** [comment]
I can't test it, but I'll take a look as soon as it's on staging or live.

**Comment by jospoortvliet** [comment]
It's fixed and live.
