### ISSUE TITLE
Get owncloud.org added to HSTS preload list

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/owncloud.org#845]
We should get owncloud.org added [to the HSTS preload lists](https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.json), this means that all browsers using this list (IE, Firefox, Chrome) will always use HTTPS when connecting to *.owncloud.org even when the website has not been visited before.

For this we need to ensure that:
1. All subdomains of owncloud.org are accessible via HTTPS
2. Set `Strict-Transport-Security: max-age=10886400; includeSubDomains; preload` on owncloud.org
3. Submit at https://hstspreload.appspot.com/

@danimo @karlitschek Can one of you check what domains we have on owncloud.org in our DNS? I know of stats.owncloud.org, download.owncloud.org, www.owncloud.org which are all accessible via HTTPS already.

**Comment by LukasReschke** [comment]
Note: owncloud.com is unlikely at the moment probably due to our internal services using that. At least until we get valid certificates everywhere there as well.

**Comment by danimo** [comment]
my understanding is that we need to have download.owncloud.org available http-only (due to repos, etc). This may be obsolete, but better make sure with @karlitschek, and escalate slowly (301 -> HSTS -> HSTS preload).

**Comment by LukasReschke** [comment]
If download.owncloud.org must be accessible via HTTP only for everything else than browsers this should not be problem. Preloading is currently only supported by browsers, cURL and Co. will not care about it.

We do also not require a 302 or 301 on any subdomain for this. However, a complete migration would certainly be desirable at some point :smile:

**Comment by hurradieweltgehtunter** [comment]
SLL cert is installed and valid for owncloud.org. 
Closing this because oooooold.

**Comment by danimo** [comment]
This is _not_ the same as HSTS preload. Old is not a good reason to close issues. See our comments above about the risks involved with this. should negligible these days.

**Comment by Kawohl** [comment]
@tboerger any thoughts?
@jnweiger

**Comment by hurradieweltgehtunter** [comment]
Ok thanks for clarifying and reopening. I hoped this was done with the relaunch but obviously not.

**Comment by tboerger** [comment]
If I take https://securityheaders.io/?q=owncloud.org&followRedirects=on for reference there is lot of space for improvement. Please enable these headers through the .htaccess file of the Wordpress instance.
