### ISSUE TITLE
older versions of owncloud client for Linux

### ISSUE THREAD

**Issue by sroubekf** [owncloud/owncloud.org#846]
Would it be possible to provide older versions, in particular 2.0.2, for Linux distributions? Current links on the web all point to the version 2.1.  The owncloud server, which my institution provides, has problems with the new version 2.1 and I need to revert back to 2.0.2. I have OpenSUSE 13.2.

**Comment by danimo** [comment]
Unfortunately this is not easily possible, as we rely on OBS which only provides the last vesion. However, you can try the latest 2.1.1 release candidate from the testing repository (https://owncloud.org/install/#testing-development). It solves many known issues from 2.1.0. If it doesn't solve the issue, we'd like to hear about the problem. Please open a separate bug report with an exact description of the problem and how to reproduce it.
