### ISSUE TITLE
ownCloud Community to Enterprise Migration

### ISSUE THREAD

**Issue by akkezi** [owncloud/owncloud.org#852]
How to migrate the community installed version to enterprise ?

**Comment by danimo** [comment]
This is the bugtracker for the ownCloud community website. For information on the enterprise version, please contact your support/presales representative, who will be happy to help you.

**Comment by akkezi** [comment]
I contacted the sales by email but no response for almost two months.
**it's very weird**

**Comment by jospoortvliet** [comment]
@akkezi that is weird and should not happen, indeed. Can you shoot me an email on jos @ owncloud com??
