### ISSUE TITLE
9.0 RC1 not available on testing page

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#882]
Hi,

oC 9.0 RC1 was announced at:

http://owncloud.10557.n7.nabble.com/Fwd-Eng-9-0-0-RC1-td16764.html

but https://owncloud.org/install/#testing-development still has beta 2

**Comment by jospoortvliet** [comment]
I added it now.

**Comment by jospoortvliet** [comment]
(thanks for reporting)

**Comment by RealRancor** [comment]
@jospoortvliet Sorry for the double work but now RC2 is out :-/

http://owncloud.10557.n7.nabble.com/9-0-0-RC2-archives-tp16801.html
