### ISSUE TITLE
Some of the Client-Logo links in the home-page are broken

### ISSUE THREAD

**Issue by aspdye** [owncloud/owncloud.org#904]

**Comment by jospoortvliet** [comment]
I can't find any broken links. Details or it didn't happen ;-)

**Comment by aspdye** [comment]
Bauhaus, Joyglobal, DeLonghi and many other Objects in this sections are only redirecting to "owncloud.org". In my opinion, they should link to a site of the company, or of the ownCloud Inc. :wink:

**Comment by jospoortvliet** [comment]
@aspdye ah, that's what you mean. Yeah, they have no customer story and I don't want to link to their sites - that's like rewarding them for not having done a customer story with ownCloud.com ;-)

I think I'll just link them to owncloud.com/customer-stories - thanks for reporting ;-)
