### ISSUE TITLE
Link to announcements fails from changelog

### ISSUE THREAD

**Issue by jeppebundsgaard** [owncloud/owncloud.org#906]
At this page: https://owncloud.org/changelog/ there is a link to this https://owncloud.org/blog/owncloud-server-9-0-released-with-improved-scalability-federation-and-collaboration - but it gives a not found error.

**Comment by RealRancor** [comment]
@jospoortvliet fixed that recently.

**Comment by jospoortvliet** [comment]
Yeah, thanks, @jeppebundsgaard this should be fixed now.
