### ISSUE TITLE
Add link/references to "owncloud-files" repository

### ISSUE THREAD

**Issue by RealRancor** [owncloud/owncloud.org#910]
Follow-up of https://github.com/owncloud/core/issues/23188#issuecomment-198323194:

With oC9.0 https://download.owncloud.org/download/repositories/stable/owncloud-files/ was introduced for systems not fully supported. However there are no notes about that at the owncloud.org pages:

> https://owncloud.org/install/#instructions-server -> Only links to https://download.owncloud.org/download/repositories/stable/owncloud/
>
> https://owncloud.org/changelog -> Only linking to https://download.owncloud.org/download/repositories/9.0/owncloud/ and https://download.owncloud.org/download/repositories/stable/owncloud/
>
> https://owncloud.org/blog/time-to-upgrade-to-owncloud-9-0/ -> Is only talking about a "owncloud-files" package, no note about that extra page with different instructions.

cc @jospoortvliet

**Comment by jnweiger** [comment]
I am looking into fixing repo_admin.py, so that both owncloud and owncloud-files can be advertised on the same web page. How about this?

**Comment by jnweiger** [comment]
https://download.owncloud.org/download/repositories/stable/owncloud/ now features both, owncloud and owncloud-files packages.

**Comment by RealRancor** [comment]
Way better, thank you for your effort. So case closed from my PoV :-)

**Comment by jnweiger** [comment]
Thanks! @jospoortvliet please close, if all that is fine with you.

**Comment by jospoortvliet** [comment]
Great solution, yes!
