### ISSUE TITLE
Update Client Screenshots

### ISSUE THREAD

**Issue by aspdye** [owncloud/owncloud.org#920]
https://owncloud.org/install is currently showing old and outdated pictures when you want to download Mobile or Desktop Clients. The Desktop Screenshot is showing an OS X Version older than 2 years, with an outdated design. Same for the Android Mockup showing Android 4.3 or lower, without Material Design :grin: 

I think we should:

- Update them
- Add an iOS Screenshot to Mobile Clients

Should i take care of this? 

cc @jospoortvliet @jancborchardt

**Comment by jancborchardt** [comment]
cc @carlaschroder for screenshots amd @rperezb for mobile apps.

**Comment by rperezb** [comment]
probably we don't have to call @carlaschroder  but @kelleybrooks or @jospoortvliet 
Feel free to ping me for the updated images for the mobile apps

**Comment by kelleybrooks** [comment]
Will let @jospoortvliet handle .org updates, but happy to arrange any similar updates for .com

**Comment by jospoortvliet** [comment]
@aspdye if you feel like it, go ahead and make the change ;-)

There are screenshots in https://github.com/owncloud/screenshots - @rperezb updates would indeed be welcome. You can email them to me if you like.

**Comment by rperezb** [comment]
@jospoortvliet I have just shared with you a couple of folders (one iOS and another Android) where we store the screenshots

**Comment by jospoortvliet** [comment]
Done. Will go live with next deploy. https://github.com/owncloud/owncloud.org/commit/db8f870ce479be59703c17776285bd769a66d870 and https://github.com/owncloud/owncloud.org/commit/db8f870ce479be59703c17776285bd769a66d870
