### ISSUE TITLE
owncloud.org not updated for 9.0.2 / 8.2.4 / ...

### ISSUE THREAD

**Issue by tessus** [owncloud/owncloud.org#956]
There's no changelog for the new versions which were released 2 days ago.
Also the download links show the old version numbers.

**Comment by RealRancor** [comment]
@tessus See https://github.com/owncloud/owncloud.org/pull/955

Known and will be released / published once some one thinks it should be released

**Comment by RealRancor** [comment]
Ah, just remembered that @jospoortvliet told in IRC that those versions are only announced once the VM images are there.

**Comment by tessus** [comment]
@RealRancor ok, but tI don't quite understand. 
The wiki states the release dates and the releases were tagged on those days, so not to put them on the web site makes no sense. At least it is not very consistent. VM images are a goddie and not the main distribution channel.

**Comment by RealRancor** [comment]
Release stuff where never really consistent. :-)

**Comment by jospoortvliet** [comment]
I usually try only to announce when everything is there. In this case, I still have no idea about the status of the VM images so I decided to push it live last night...

It is, on one hand, true that the VM's are 'sugar' but if you're thinking you'll get 9.0.2 and you download a 1gb VM and it is 9.0.1 - that's uncool... :-1: 

Anyhow, it is live now.
