### ISSUE TITLE
New installation of Ubuntu 16.04 and Owncloud 9.0.2 doesn't work

### ISSUE THREAD

**Issue by kasra7** [owncloud/owncloud.org#962]
Hi
I have problem with logging to web panel.(owncloud was not found on this server)
Localhost/owncloud/index.php doesn't work.

**Server configuration**
Operating system: Ubuntu 16.04
Web server: Apache/2.4.18 (Ubuntu) 
Database: mysql 5.7
PHP version: 7.0
OwnCloud version 9 (http://download.owncloud.org/download/repositories/stable/xUbuntu_16.04)

**Comment by RealRancor** [comment]
@kasra7 This is the wrong repositoriy:

> Development repository for the owncloud.org website

Please close here and ask for support at the forums or users mailinglist https://owncloud.org/support/ . There such setup questions belongs to.
