### ISSUE TITLE
Can't download old version from https://owncloud.org/changelog/

### ISSUE THREAD

**Issue by achakabuba** [owncloud/owncloud.org#969]
Hi!
I have 5.0.12 version of OwnCloud. I want to update it to higher versions.
Some users said that it must be - 5.0.12 - 5.0.19 - 6.0.9 - 7.0.15 - etc.
But at this page https://owncloud.org/changelog i can't download versions 5.0.19 & 6.0.9 (The requested URL /community/owncloud-6.0.9.zip was not found on this server.)
Maybe someone can share this versions for me? (for windows)
Thx.

**Comment by danimo** [comment]
Windows has been discontinued as a server platform for ownCloud. Please see https://owncloud.org/blog/owncloud-server-8-1-will-not-support-windows-as-server-platform-natively/ for alternatives.

**Comment by RealRancor** [comment]
Aside from the unsupported windows the old releases should be put up again. That was already requested in https://github.com/owncloud/core/issues/23885
