### ISSUE TITLE
Download links for Release 6.0.9 broken

### ISSUE THREAD

**Issue by leafnode** [owncloud/owncloud.org#972]
Every download link in Release 6.0.9 section is broken - one directory level (/6/) is missing.

**Comment by danimo** [comment]
Where do you even see that still? 6.x is out of maintenance for quite a while now...

**Comment by leafnode** [comment]
https://owncloud.org/changelog/#latest6

Yeah, I know it's out of maintenance, but I had OC5 instance, and I wanted to upgrade it step-by-step, hence OC6 was needed.

**Comment by danimo** [comment]
Thanks for lettings us know. Fixed.
