### ISSUE TITLE
Errors in setup-owncloud.php

### ISSUE THREAD

**Issue by jonathancross** [owncloud/owncloud.org#975]
Hi there.
There are some broken links in this file:
https://download.owncloud.com/download/community/setup-owncloud.php

It is referenced from the ["web installer" tab](https://owncloud.org/install/#instructions-server).

The filename and content match this [setup-owncloud.php](https://github.com/owncloud/administration/blob/master/web-installer/setup-owncloud.php), but the path doesn't match.

Seems to have broken links to the following resources:
* https://owncloud.org/setupwizard/styles.css
* https://owncloud.org/setupwizard/logo.png
* https://owncloud.org/setupwizard/favicon.png

**Comment by RealRancor** [comment]
Could you reopen this in https://github.com/owncloud/administration/issues where issues within the setup-owncloud.php are tracked

**Comment by jonathancross** [comment]
Done: https://github.com/owncloud/administration/issues/85
