### ISSUE TITLE
Layout of »7« page

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/owncloud.org#98]
Comparing the layout of http://owncloud.org/7 with http://owncloud.org/six – the old one (six or /features) looks way better. More visual, no strange hidden slideout stuff with lots. of. text. and just way easier to browse.

Can we do the same for owncloud.org/7? No need to change the layout, it’s great.

What do you think @tomneedham @kelleybrooks @jospoortvliet?

**Comment by jospoortvliet** [comment]
Fixed, eight layout same as features page.

**Comment by jancborchardt** [comment]
Good stuff.

For the things like »Federated Cloud«, »Favorites« etc we could make the images bigger (and center them in the column) and reduce the text a bit, but otherwise it’s fine.

**Comment by jospoortvliet** [comment]
We'll do better for 8.1, OK ? :D

**Comment by jancborchardt** [comment]
Ayyup!
