### ISSUE TITLE
Change CLA FAQ address

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud.org#987]
The CLA address still shows the address with Carlos' name and the US office.

Should it be changed to be the Nüremberg office ?

@hodyroff @danimo @dragotin

**Comment by PVince81** [comment]
here https://owncloud.org/contribute/agreement/, search for "carlos"

**Comment by DeepDiver1975** [comment]
by intention at the moment - has legal background
will be resolved next week

**Comment by danimo** [comment]
Addressed by #988
