### ISSUE TITLE
404 for linux packages

### ISSUE THREAD

**Issue by ManOki** [owncloud/owncloud.org#989]
Hi,

i can't update my owncloud instance anymore via owncloud.org linux packages, because i'm getting 404 on
https://download.owncloud.org/download/repositories/stable/owncloud

This Link is listed from the main website on tab "Packages": https://owncloud.org/install/#instructions-server

Greets,
ManOki

**Comment by PVince81** [comment]
Thanks for the info, we're looking into it.

In the meantime the versioned URLs still work, like https://download.owncloud.org/download/repositories/9.0/owncloud so if you need to update quickly you could use those.

@danimo @jnweiger @michaelstingl

**Comment by Kawohl** [comment]
Hey @ManOki  Sysadmins are on it.

**Comment by jnweiger** [comment]
We hit a disk full error. sorry for that. 
Everything is recovered by now.
